Repository Vizzuality/marxan-cloud, pull requests merged in 2020-12, with the labels that each got.

#6 Icon
  app/.storybook/main.js
  app/.storybook/manager.js
  app/.storybook/preview-head.html
  app/components/icon/component.stories.tsx
  app/components/icon/component.tsx
  app/local.d.ts
  app/next.config.js
  app/package.json
  app/svgs/social/facebook.svg
  app/svgs/social/instagram.svg
  app/svgs/social/linkedin.svg
  app/svgs/social/twitter.svg
  app/svgs/ui/arrow-down.svg
  app/svgs/ui/arrow-left.svg
  app/svgs/ui/arrow-right.svg
  app/svgs/ui/arrow-up.svg
  app/svgs/ui/checkbox-on.svg
  app/svgs/ui/close.svg
  app/svgs/ui/download.svg
  app/svgs/ui/glossary.svg
  app/svgs/ui/help.svg
  app/svgs/ui/info.svg
  app/svgs/ui/methodology.svg
  app/svgs/ui/pause.svg
  app/svgs/ui/play.svg
  app/svgs/ui/plus.svg
  app/svgs/ui/remove.svg
  app/svgs/ui/search.svg
  app/svgs/ui/share.svg
  app/yarn.lock
Labels: Frontend, Ready to review, documentation

#7 Feature/prettier config
  .editorconfig
  .gitattributes
  app/.prettierrc.js
  app/package.json
Labels: Frontend, Ready to review

#8 Forms
  app/components/forms/component.stories.tsx
  app/components/forms/field/component.stories.tsx
  app/components/forms/field/component.tsx
  app/components/forms/field/index.ts
  app/components/forms/input/component.stories.tsx
  app/components/forms/input/component.tsx
  app/components/forms/input/index.ts
  app/components/forms/textarea/component.stories.tsx
  app/components/forms/textarea/component.tsx
  app/components/forms/textarea/index.ts
  app/components/forms/validations.ts
  app/package.json
  app/tailwind.config.js
  app/yarn.lock
Labels: Frontend, Ready to review, documentation

#12 setup for PostgreSQL+PostGIS container for API data layer
  Makefile
  README.md
  docker-compose.yml
  env.default
  postgresql/Dockerfile
Labels: API

#13 set up DB connection+ORM for API service
  api/Dockerfile
  api/config/custom-environment-variables.json
  api/ormconfig.ts
  api/package.json
  api/src/app.module.ts
  api/tsconfig.json
Labels: API

#16 Map component + Layer manager
  app/.storybook/preview.js
  app/components/map/component.stories.tsx
  app/components/map/component.tsx
  app/components/map/index.ts
  app/components/map/layers.ts
  app/package.json
  app/yarn.lock
Labels: Frontend, Ready to review, documentation

#17 Map controls
  app/.eslintrc.js
  app/components/map/component.stories.tsx
  app/components/map/component.tsx
  app/components/map/controls/component.stories.tsx
  app/components/map/controls/component.tsx
  app/components/map/controls/fit-bounds/component.stories.tsx
  app/components/map/controls/fit-bounds/component.tsx
  app/components/map/controls/fit-bounds/index.ts
  app/components/map/controls/index.ts
  app/components/map/controls/zoom/component.stories.tsx
  app/components/map/controls/zoom/component.tsx
  app/components/map/controls/zoom/index.ts
  app/package.json
  app/svgs/map/fit-bounds.svg
  app/svgs/map/zoom-in.svg
  app/svgs/map/zoom-out.svg
  app/yarn.lock
Labels: Frontend, Ready to review, documentation
