Repository Vizzuality/marxan-cloud, pull requests merged in 2020-11, with the labels that each got.

#1 Feature/add css utils adr
  .github/pull_request_template.md
  docs/adr/0000_using-tailwind.css-as-styles-utility-library.md
Labels: documentation

#2 Front-end setup
  app/.eslintrc.js
  app/.gitignore
  app/.nvmrc
  app/.prettierrc.js
  app/CHANGELOG.md
  app/Dockerfile
  app/README.md
  app/components/header/component.tsx
  app/components/header/index.ts
  app/components/icon/component.tsx
  app/components/icon/index.ts
  app/dummy.js
  app/entrypoint.sh
  app/next-env.d.ts
  app/now.json
  app/package.json
  app/pages/_app.tsx
  app/pages/index.tsx
  app/postcss.config.js
  app/public/favicon.ico
  app/public/vercel.svg
  app/styles/tailwind.css
  app/tailwind.config.js
  app/tsconfig.json
Labels: Frontend, Ready to review

#4 Storybook
  app/.gitignore
  app/.storybook/.babelrc
  app/.storybook/main.js
  app/.storybook/preview-head.html
  app/.storybook/preview.js
  app/components/header/component.stories.tsx
  app/components/icon/component.stories.tsx
  app/package.json
  app/public/styles/tailwind.storybook.css
  app/yarn.lock
Labels: Frontend, Ready to review, documentation
