Repository Vizzuality/marxan-cloud, pull requests merged in 2021-11, with the labels that each got.

#609 Fix(front): planning area [MARXAN-952][MARXAN-950][MARXA-938]
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/layout/projects/new/form/component.tsx
  app/layout/projects/new/form/constants.ts
  app/layout/projects/new/form/planning-area-grid-uploader/component.tsx
  app/layout/projects/new/form/planning-area-uploader/component.tsx
  app/layout/projects/new/map/component.tsx
  app/layout/projects/new/map/types.ts
Labels: bug, Frontend, WIP

#615 Fix(front):[MARXAN-954][MARXAN-938]
  app/hooks/map/index.ts
  app/layout/projects/new/form/planning-area-grid-uploader/component.tsx
  app/layout/projects/new/form/planning-area-uploader/component.tsx
  app/layout/scenarios/show/map/component.tsx
  app/store/slices/scenarios/detail.ts
Labels: bug, Frontend

#616 fix(front): [MARXAN-962][MARXAN-949]
  app/layout/me/reset-password/component.tsx
  app/layout/projects/new/form/component.tsx
  app/layout/projects/new/form/country-region-selector/component.tsx
  app/layout/projects/new/form/country-region-selector/types.ts
  app/layout/projects/new/form/planning-area-selector/component.tsx
  app/store/slices/scenarios/detail.ts
Labels: bug, Frontend

#620 Feat(front): [MARXAN-685][MARXAN-969]
  app/layout/header/component.tsx
  app/layout/header/title/component.tsx
  app/layout/me/reset-password/component.tsx
  app/layout/projects/show/header/component.tsx
  app/layout/projects/show/header/description/component.tsx
  app/layout/projects/show/header/description/index.ts
  app/layout/projects/show/scenarios/component.tsx
  app/layout/projects/show/scenarios/filters/component.tsx
  app/layout/projects/show/scenarios/toolbar/component.tsx
  app/svgs/project/edit.svg
Labels: Ready to review

#623 Fix(front):[MARXAN-934][MARXAN-990][MARXAN-933][MARXAN-940][MARXAN-888][MARXAN-935]
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/layout/header/title/component.tsx
  app/layout/me/profile/avatar/component.tsx
  app/layout/projects/new/form/planning-area-grid-uploader/component.tsx
  app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/component.tsx
  app/layout/projects/new/form/planning-area-uploader/component.tsx
  app/layout/projects/show/header/title/component.tsx
  app/layout/projects/show/map/component.tsx
  app/layout/scenarios/edit/analysis/cost-surface/component.tsx
  app/layout/scenarios/edit/features/add/uploader/component.tsx
  app/layout/scenarios/edit/features/intersect/component.tsx
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/edit/status/component.tsx
Labels: bug, Frontend, Ready to review

#631 Fix(front):[MARXAN-1030]
  app/components/forms/select/component.tsx
  app/components/forms/select/multi/component.tsx
  app/components/forms/select/single/component.tsx
Labels: bug, Frontend, Ready to review

#633 Fix(front): exclude-include pu on top of default ones[MARXAN-968]
  app/hooks/scenarios/index.ts
Labels: bug, Frontend

#635 Fix(front):[MARXAN-935][MARXAN-965]
  app/hooks/features/index.ts
  app/hooks/published-projects/index.ts
  app/layout/forgot-password/component.tsx
  app/pages/api/auth/[...nextauth].ts
Labels: bug, Frontend

#614 added new data seeds
  Makefile
  api/apps/api/test/countries.e2e-spec.ts
  api/apps/api/test/fixtures/features/demo_acinonyx_jubatus.sql
  api/apps/api/test/fixtures/features/demo_bucorvus_leadbeateri.sql
  api/apps/api/test/fixtures/features/demo_ceratotherium_simum.sql
  api/apps/api/test/fixtures/features/demo_civettictis_civetta.sql
  api/apps/api/test/fixtures/features/demo_diceros_bicornis.sql
  api/apps/api/test/fixtures/features/demo_equus_quagga.sql
  api/apps/api/test/fixtures/features/demo_giraffa_camelopardalis.sql
  api/apps/api/test/fixtures/features/demo_kobus_leche.sql
  api/apps/api/test/fixtures/features/demo_panthera_pardus.sql
  api/apps/api/test/fixtures/features/iucn_acinonyxjubatus.sql
  api/apps/api/test/fixtures/features/iucn_anomalurusderbianus.sql
  api/apps/api/test/fixtures/features/iucn_antidorcasmarsupialis.sql
  api/apps/api/test/fixtures/features/iucn_aonyxcapensis.sql
  api/apps/api/test/fixtures/features/iucn_crocidurahirta.sql
  api/apps/api/test/fixtures/features/iucn_dendrohyraxarboreus.sql
  api/apps/api/test/fixtures/features/iucn_epomophoruswahlbergi.sql
  api/apps/api/test/fixtures/features/iucn_otolemurcrassicaudatus.sql
  api/apps/api/test/fixtures/features/iucn_pantherapardus.sql
  api/apps/api/test/fixtures/test-admin-data.sql
  api/apps/api/test/fixtures/test-data.sql
  api/apps/api/test/fixtures/test-features.sql
  api/apps/api/test/fixtures/test-geodata.sql
  api/apps/api/test/fixtures/test-wdpa-data.sql
  api/apps/api/test/geo-features.e2e-spec.ts
  api/apps/api/test/proxy.vector-tiles.e2e-spec.ts
  api/apps/api/test/scenario-features/get-scenario-features.e2e-spec.ts
  api/apps/api/test/scenario-features/steps/when-scenario-has-pre-gap-data.ts
  api/apps/geoprocessing/test/tiles/protected-area.fixtures.ts
  data/notebooks/Lab/convert_csv_sql.ipynb
Labels: Data

#632 MARXAN-1004 Updates in projects ACL
  api/apps/api/src/migrations/api/1636715822155-Roles-Updates.ts
  api/apps/api/src/modules/access-control/access-control-service.interface.ts
  api/apps/api/src/modules/access-control/access-control.module.ts
  api/apps/api/src/modules/access-control/access-control.types.ts
  api/apps/api/src/modules/access-control/index.ts
  api/apps/api/src/modules/access-control/projects-acl/project-access-control.ts
  api/apps/api/src/modules/access-control/projects-acl/project-acl.service.spec.ts
  api/apps/api/src/modules/access-control/projects-acl/project-acl.service.ts
  api/apps/api/src/modules/projects-acl/index.ts
  api/apps/api/src/modules/projects-acl/project-acl.module.ts
  api/apps/api/src/modules/projects-acl/project-acl.service.spec.ts
  api/apps/api/src/modules/projects-acl/project-acl.service.ts
  api/apps/api/src/modules/projects/control-level/users-projects.api.entity.ts
  api/apps/api/src/modules/published-project/published-project.module.ts
  api/apps/api/src/modules/published-project/published-project.service.ts
  api/apps/api/src/modules/users/role.api.entity.ts
  api/apps/api/test/fixtures/test-data.sql
Labels: API

#629 Updated functions and data for most different solution
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/__tests__/solutions.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/geo-output/geo-output.repository.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/geo-output/solutions/planning-unit-selection-state.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/geo-output/solutions/solution-aggregation/planning-unit-selection-calculator.service.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/geo-output/solutions/solution-aggregation/planning-unit-state-calculator.service.spec.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/most-different.service.spec.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/most-different.service.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/result-parser.service.spec.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/result-parser.service.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/solutions-output.service.ts
  api/libs/marxan-output/src/execution-result.ts
  data/notebooks/Lab/5-most-different-solution-algorithm.ipynb
  data/notebooks/Lab/marxan_utils.ipynb
Labels: API, WIP

#648 Feat(front): change texts
  app/layout/projects/show/scenarios/component.tsx
  app/layout/projects/show/scenarios/types/component.tsx
  app/layout/scenarios/edit/analysis/cost-surface/component.tsx
  app/layout/scenarios/edit/status/constants.ts
Labels: Frontend, WIP

#656 fix(front): uploading big size files to adjust planning units
  app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/uploading/component.tsx
Labels: bug, Frontend, Ready to review

#652 feat(front): sign up confirmation
  app/hooks/me/index.ts
  app/hooks/me/types.ts
  app/layout/me/sign-up-confirmation/component.tsx
  app/layout/sign-up/component.tsx
Labels: Frontend, WIP, New feature
