Repository Vizzuality/marxan-cloud, pull requests merged in 2021-07, with the labels that each got.

#302 Feat/marxan 455/about [MARXAN-455]
  app/components/button/component.stories.tsx
  app/components/button/component.tsx
  app/layout/about/utilities/component.tsx
  app/layout/about/utilities/constants.ts
  app/layout/about/utilities/index.ts
  app/layout/about/values/component.tsx
  app/layout/about/values/constants.ts
  app/layout/about/values/index.ts
  app/layout/statics/button-link/component.tsx
  app/layout/statics/button-link/index.ts
  app/layout/statics/contact/component.tsx
  app/layout/statics/contact/index.ts
  app/layout/statics/hero/component.tsx
  app/layout/statics/hero/index.ts
  app/pages/about.tsx
  app/public/styles/tailwind.storybook.css
Labels: Frontend, New feature, WIP

#310 Feat/marxan 455/marxan 458/partners [MARXAN-458]
  app/layout/footer/component.tsx
  app/layout/header/component.tsx
  app/layout/header/my-projects/component.tsx
  app/layout/partners/component.tsx
  app/layout/partners/constants.ts
  app/layout/partners/index.ts
  app/layout/wrapper/component.tsx
  app/pages/partners.tsx
  app/public/styles/tailwind.storybook.css
  app/svgs/partners/biopama_logo.svg
  app/svgs/partners/eu_logo.svg
  app/svgs/partners/mapbox_logo.svg
  app/svgs/partners/microsoft_logo.svg
  app/svgs/partners/pacmara_logo.svg
  app/svgs/partners/the-nature-conservancy_logo.svg
  app/svgs/partners/un-environment_logo.svg
  app/svgs/partners/university-queensland_logo.svg
  app/svgs/partners/vizzuality_logo.svg
Labels: Frontend, New feature, WIP

#318 Feat/marxan 513/community published projects detail [MARXAN-513]
  app/.storybook/preview.js
  app/components/projects/item/component.tsx
  app/components/projects/published-item/component.stories.tsx
  app/components/projects/published-item/component.tsx
  app/hooks/projects/index.ts
  app/layout/community/component.tsx
  app/layout/community/published-projects/component.tsx
  app/layout/community/published-projects/detail/component.tsx
  app/layout/community/published-projects/detail/map/component.tsx
  app/layout/community/published-projects/detail/map/index.ts
  app/layout/community/published-projects/detail/share/component.tsx
  app/layout/community/published-projects/detail/share/index.ts
  app/layout/community/published-projects/duplicate-button/component.tsx
  app/layout/community/published-projects/duplicate-button/index.ts
  app/layout/partners/component.tsx
  app/layout/statics/contact/component.tsx
  app/svgs/social/facebook-filled.svg
  app/svgs/social/link.svg
  app/svgs/social/twitter-filled.svg
  app/svgs/ui/checked.svg
  app/types/project-model.ts
Labels: Frontend, New feature, WIP

#305 output entities migration ready + fake data for outputs
  api/apps/api/src/migrations/api/1624890503611-marxanOutputEntities.ts
  api/apps/api/src/modules/scenarios/dto/scenario-solution-result.dto.ts
  api/apps/api/src/modules/scenarios/dto/scenario-solution.serializer.ts
  api/apps/api/src/modules/scenarios/scenarios.controller.ts
  api/apps/api/src/modules/scenarios/scenarios.module.ts
  api/apps/api/src/modules/scenarios/scenarios.service.ts
  api/apps/api/src/modules/scenarios/solutions-result/solution-result-crud.service.ts
  api/apps/api/test/fixtures/test-data.sql
  api/apps/api/test/fixtures/test-geodata.sql
  api/apps/api/test/scenario-solutions/get-all-solutions.e2e-spec.ts
  api/apps/api/test/scenario-solutions/world.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/solutions-output.service.ts
  api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandboxed-runner.module.ts
  api/apps/geoprocessing/src/migrations/geoprocessing/1624890503611-marxanOutputEntities.ts
  api/apps/geoprocessing/src/modules/planning-units/planning-units.job.ts
  api/apps/geoprocessing/src/modules/scenarios/cost-template/cost-template-dumper.ts
  api/apps/geoprocessing/src/modules/surface-cost/adapters/typeorm-cost-surface.ts
  api/apps/geoprocessing/test/cost-template/cost-template-worker.e2e-spec.ts
  api/apps/geoprocessing/test/integration/cost-surface/cost-surface-job/process-shapefile-with-cost-surface.e2e-spec.ts
  api/apps/geoprocessing/test/integration/cost-surface/cost-surface-job/steps/world.ts
  api/apps/geoprocessing/test/integration/cost-surface/cost-surface-repo/cost-surface-update.e2e-spec.ts
  api/apps/geoprocessing/test/integration/cost-surface/planning-unit-fixtures.ts
  api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
  api/apps/geoprocessing/test/worker-module/worker-module-di-usage.e2e-spec.ts
  api/libs/scenarios-planning-unit/src/index.ts
  api/libs/scenarios-planning-unit/src/scenarios-output-results.geo.entity.ts
  api/libs/scenarios-planning-unit/src/scenarios-outputs-summaries.api.entity.ts
  api/libs/scenarios-planning-unit/src/scenarios-pu-cost-data.geo.entity.ts
  api/libs/scenarios-planning-unit/src/scenarios-pu-output.geo.entity.ts
  data/notebooks/Lab/datfilesCreationFromDB_logic.ipynb
  data/notebooks/Lab/featuresForScenario_logic.ipynb
  data/notebooks/Lab/marxan_utils.ipynb
  data/notebooks/Lab/outputFilesToDB.ipynb
Labels: WIP

#320 Geofeatures recipes
  app/components/features/intersect-item/component.tsx
  app/components/features/selected-item/component.tsx
  app/components/features/target-spf-item/component.tsx
  app/components/modal/component.tsx
  app/hooks/features/index.ts
  app/hooks/features/types.ts
  app/hooks/scenarios/index.ts
  app/layout/projects/show/scenarios/component.tsx
  app/layout/scenarios/sidebar/features/add/component.tsx
  app/layout/scenarios/sidebar/features/component.tsx
  app/layout/scenarios/sidebar/features/intersect/component.tsx
  app/layout/scenarios/sidebar/features/intersect/list/component.tsx
  app/layout/scenarios/sidebar/features/list/component.tsx
  app/layout/scenarios/sidebar/features/targets/component.tsx
  app/pages/_app.tsx
  app/services/geo-features/index.ts
Labels: Frontend, New feature, Ready to review

#325 Feat/app/carousel [MARXAN-517]
  app/components/carousel/component.stories.tsx
  app/components/carousel/component.tsx
  app/components/carousel/index.ts
  app/images/carousel-1.png
  app/images/carousel-2.png
  app/images/carousel-3.png
  app/images/carousel-4.png
  app/layout/about/utilities/component.tsx
  app/layout/home/carousel-section/component.tsx
  app/layout/home/carousel-section/constants.ts
  app/layout/home/carousel-section/index.ts
  app/layout/home/features/component.tsx
  app/layout/statics/button-link/component.tsx
  app/package.json
  app/pages/index.tsx
  app/public/styles/tailwind.storybook.css
  app/styles/tailwind.css
  app/tsconfig.json
  app/yarn.lock
Labels: Frontend, New feature, Ready to review

#327 Community
  app/.storybook/preview.js
  app/components/avatar/component.tsx
  app/components/button/component.stories.tsx
  app/components/button/component.tsx
  app/components/projects/item/component.tsx
  app/components/projects/published-item/component.stories.tsx
  app/components/projects/published-item/component.tsx
  app/components/projects/published-item/index.ts
  app/hooks/projects/index.ts
  app/hooks/projects/types.ts
  app/hooks/scenarios/index.ts
  app/layout/about/utilities/component.tsx
  app/layout/about/values/component.tsx
  app/layout/about/values/constants.ts
  app/layout/community/component.tsx
  app/layout/community/index.ts
  app/layout/community/published-projects/component.tsx
  app/layout/community/published-projects/detail/component.tsx
  app/layout/community/published-projects/detail/index.ts
  app/layout/community/published-projects/detail/map/component.tsx
  app/layout/community/published-projects/detail/map/index.ts
  app/layout/community/published-projects/detail/share/component.tsx
  app/layout/community/published-projects/detail/share/index.ts
  app/layout/community/published-projects/duplicate-button/component.tsx
  app/layout/community/published-projects/duplicate-button/index.ts
  app/layout/community/published-projects/index.ts
  app/layout/footer/component.tsx
  app/layout/header/component.tsx
  app/layout/statics/backlink/component.tsx
  app/layout/statics/backlink/index.ts
  app/layout/statics/button-link/component.tsx
  app/layout/statics/column/component.tsx
  app/layout/statics/column/index.ts
  app/layout/statics/contact/component.tsx
  app/layout/statics/hero/component.tsx
  app/pages/community/index.tsx
  app/pages/community/projects/[pid]/index.tsx
  app/pages/community/projects/index.tsx
  app/store/index.ts
  app/store/slices/community/projects/index.ts
  app/svgs/social/facebook-filled.svg
  app/svgs/social/link.svg
  app/svgs/social/twitter-filled.svg
  app/svgs/ui/checked.svg
  app/tailwind.config.js
  app/types/project-model.ts
Labels: Frontend, New feature, Ready to review

#322 Help: Projects & Project detail
  app/layout/help/beacon/component.tsx
  app/layout/help/spotlight/component.tsx
  app/layout/projects/all/list/component.tsx
  app/layout/projects/all/toolbar/component.tsx
  app/layout/projects/show/header/toolbar/component.tsx
  app/layout/projects/show/map/component.tsx
  app/layout/projects/show/scenarios/component.tsx
Labels: Frontend, New feature, Ready to review

#297 PU grid layer
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/layout/scenarios/map/component.tsx
Labels: Frontend, New feature, WIP

#333 feat(front): upload shapefile on new project [MARXAN-519]
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/hooks/projects/index.ts
  app/hooks/projects/types.ts
  app/layout/projects/new/form/component.tsx
  app/layout/projects/new/form/country-region-selector/component.tsx
  app/layout/projects/new/form/country-region-selector/index.ts
  app/layout/projects/new/form/country-region-selector/types.ts
  app/layout/projects/new/form/planning-area-selector/component.tsx
  app/layout/projects/new/form/planning-area-uploader/component.tsx
  app/layout/projects/new/form/planning-area-uploader/index.ts
  app/layout/projects/new/form/types.ts
  app/layout/projects/new/map/component.tsx
  app/store/slices/projects/new.ts
Labels: Frontend, New feature, Ready to review

#345 fix(front): partners updates [MARXAN-539]
  app/images/home-carousel/carousel-1.png
  app/images/home-carousel/carousel-2.png
  app/images/home-carousel/carousel-3.png
  app/images/home-carousel/carousel-4.png
  app/images/partners/allen-coral_logo.png
  app/images/partners/biopama_logo.png
  app/images/partners/european-commission_logo.png
  app/images/partners/mapbox_logo.png
  app/images/partners/microsoft_logo.png
  app/images/partners/pacmara_logo.png
  app/images/partners/the-nature-conservancy_logo.png
  app/images/partners/un-environment_logo.png
  app/images/partners/university-queensland_logo.png
  app/images/partners/vizzuality_logo.png
  app/layout/home/carousel-section/constants.ts
  app/layout/partners/component.tsx
  app/layout/partners/constants.ts
  app/svgs/partners/biopama_logo.svg
  app/svgs/partners/eu_logo.svg
  app/svgs/partners/mapbox_logo.svg
  app/svgs/partners/microsoft_logo.svg
  app/svgs/partners/pacmara_logo.svg
  app/svgs/partners/the-nature-conservancy_logo.svg
  app/svgs/partners/un-environment_logo.svg
  app/svgs/partners/university-queensland_logo.svg
  app/svgs/partners/vizzuality_logo.svg
Labels: Frontend, Ready to review

#353 feat(front): meta icons [MARXAN-558]
  app/images/meta-icons/android-icon-144x144.png
  app/images/meta-icons/android-icon-192x192.png
  app/images/meta-icons/android-icon-36x36.png
  app/images/meta-icons/android-icon-48x48.png
  app/images/meta-icons/android-icon-72x72.png
  app/images/meta-icons/android-icon-96x96.png
  app/images/meta-icons/apple-icon-114x114.png
  app/images/meta-icons/apple-icon-120x120.png
  app/images/meta-icons/apple-icon-144x144.png
  app/images/meta-icons/apple-icon-152x152.png
  app/images/meta-icons/apple-icon-180x180.png
  app/images/meta-icons/apple-icon-57x57.png
  app/images/meta-icons/apple-icon-60x60.png
  app/images/meta-icons/apple-icon-72x72.png
  app/images/meta-icons/apple-icon-76x76.png
  app/images/meta-icons/apple-icon-precomposed.png
  app/images/meta-icons/apple-icon.png
  app/images/meta-icons/browserconfig.xml
  app/images/meta-icons/favicon-16x16.png
  app/images/meta-icons/favicon-32x32.png
  app/images/meta-icons/favicon-96x96.png
  app/images/meta-icons/favicon.ico
  app/images/meta-icons/manifest.json
  app/images/meta-icons/ms-icon-144x144.png
  app/images/meta-icons/ms-icon-150x150.png
  app/images/meta-icons/ms-icon-310x310.png
  app/images/meta-icons/ms-icon-70x70.png
  app/images/social-media/marxan-social-media.png
  app/images/social-media/share-fb.png
  app/images/social-media/share-tw.png
  app/layout/meta-icons/component.tsx
  app/layout/meta-icons/index.ts
  app/layout/meta-tags/component.tsx
  app/layout/title/project-title/component.tsx
  app/layout/title/published-project-title/component.tsx
  app/pages/404.tsx
  app/pages/about.tsx
  app/pages/auth/forgot-password.tsx
  app/pages/auth/sign-in.tsx
  app/pages/auth/sign-up.tsx
  app/pages/community/index.tsx
  app/pages/community/projects/[pid]/index.tsx
  app/pages/community/projects/index.tsx
  app/pages/index.tsx
  app/pages/me.tsx
  app/pages/partners.tsx
  app/pages/projects/[pid]/edit.tsx
  app/pages/projects/[pid]/index.tsx
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
  app/pages/projects/[pid]/scenarios/[sid]/index.tsx
  app/pages/projects/[pid]/scenarios/new.tsx
  app/pages/projects/index.tsx
  app/pages/projects/new.tsx
Labels: Frontend, New feature, Ready to review

#356 feat(front): privacy policy and terms of use pages [MARXAN-559]
  app/layout/statics/privacy-policy/component.tsx
  app/layout/statics/privacy-policy/index.ts
  app/pages/privacy-policy.tsx
  app/pages/terms-of-use.tsx
Labels: Frontend, New feature, Ready to review

#357 feat(front): register workflow improvements [MARXAN-560]
  app/components/button/component.stories.tsx
  app/components/button/component.tsx
  app/components/confirmation-prompt/component.tsx
  app/components/confirmation-prompt/types.ts
  app/layout/guide-request/component.tsx
  app/layout/guide-request/index.ts
  app/layout/me/change-password/component.tsx
  app/layout/me/component.tsx
  app/layout/me/delete-account/component.tsx
  app/layout/me/profile/component.tsx
  app/layout/protected/component.tsx
  app/layout/sign-in/component.tsx
  app/layout/sign-up/component.tsx
  app/layout/sign-up/confirm/component.tsx
  app/layout/sign-up/confirm/index.ts
  app/pages/auth/sign-up.tsx
  app/pages/me.tsx
  app/svgs/notifications/delete-user-warning.svg
  app/svgs/users/guide-request.svg
Labels: Frontend, Ready to review

#368 feat(front): matrix legend type [MARXAN-573]
  app/components/map/legend/component.stories.tsx
  app/components/map/legend/mock.tsx
  app/components/map/legend/types/matrix/component.tsx
  app/components/map/legend/types/matrix/index.ts
Labels: Frontend, New feature, Ready to review

#339 Adjust planning units: API connection
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/hooks/scenarios/index.ts
  app/hooks/scenarios/types.ts
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/clicking/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/drawing/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/uploading/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/component.tsx
  app/layout/scenarios/sidebar/analysis/component.tsx
  app/layout/scenarios/sidebar/solutions/component.tsx
  app/layout/scenarios/sidebar/wdpa/component.tsx
  app/store/slices/scenarios/edit.ts
Labels: Frontend, New feature, WIP

#373 feat: order imports eslint configs
  app/.eslintrc.js
  app/package.json
  app/yarn.lock
Labels: Frontend, Ready to review

#375 feat(front): duplicate projects and scenarios [MARXAN-599]
  app/hooks/projects/index.ts
  app/hooks/projects/types.ts
  app/hooks/scenarios/index.ts
  app/hooks/scenarios/types.ts
  app/layout/community/published-projects/detail/component.tsx
  app/layout/community/published-projects/duplicate-button/component.tsx
  app/layout/projects/all/list/component.tsx
  app/layout/projects/show/scenarios/component.tsx
Labels: Frontend, New feature, Ready to review
