Repository Vizzuality/marxan-cloud, pull requests merged in 2021-03, with the labels that each got.

#71 Select: migrate dropdowns to select component
  app/components/dropdowns/component.stories.tsx
  app/components/dropdowns/component.tsx
  app/components/dropdowns/toggle/index.ts
  app/components/features/selected-item/component.tsx
  app/components/forms/select/component.stories.tsx
  app/components/forms/select/component.tsx
  app/components/forms/select/constants/popper-modifiers.js
  app/components/forms/select/constants/theme.js
  app/components/forms/select/menu/component.tsx
  app/components/forms/select/menu/index.ts
  app/components/forms/select/multi/component.tsx
  app/components/forms/select/multi/index.ts
  app/components/forms/select/single/component.tsx
  app/components/forms/select/single/index.ts
  app/components/forms/select/toggle/component.tsx
  app/components/forms/select/toggle/index.ts
  app/components/forms/select/types.d.ts
Labels: Frontend, Ready to review, enhancement

#80 Some improvements related mostly with stronger typing
  app/components/loading/component.stories.tsx
  app/components/loading/component.tsx
  app/components/loading/types.ts
  app/components/toast/component.stories.tsx
  app/components/toast/component.tsx
  app/components/toast/types.ts
  app/components/tooltip/component.stories.tsx
  app/components/tooltip/component.tsx
  app/components/tooltip/types.ts
  app/package.json
Labels: Frontend, Ready to review

#78 Notifications
  app/components/loading/component.stories.tsx
  app/components/loading/component.tsx
  app/components/loading/types.ts
  app/components/toast/component.stories.tsx
  app/components/toast/component.tsx
  app/components/toast/index.ts
  app/components/toast/types.ts
  app/components/tooltip/component.stories.tsx
  app/components/tooltip/component.tsx
  app/components/tooltip/types.ts
  app/hooks/toast/constants.ts
  app/hooks/toast/index.tsx
  app/hooks/toast/types.ts
  app/layout/header/title/component.tsx
  app/layout/sign-in/component.tsx
  app/layout/sign-up/component.tsx
  app/layout/toast/component.tsx
  app/layout/toast/index.ts
  app/package.json
  app/pages/_app.tsx
  app/pages/index.tsx
  app/svgs/notifications/error.svg
  app/svgs/notifications/info.svg
  app/svgs/notifications/success.svg
  app/svgs/notifications/warning.svg
  app/yarn.lock
Labels: Frontend, New feature, Ready to review

#84 Select: max height
  app/components/forms/select/component.stories.tsx
  app/components/forms/select/constants/theme.js
  app/components/forms/select/multi/component.tsx
  app/components/forms/select/single/component.tsx
  app/components/forms/select/types.d.ts
Labels: Frontend, Ready to review, enhancement

#86 Update the Modal and add two prompt components
  app/.storybook/preview.js
  app/components/confirmation-prompt/component.stories.tsx
  app/components/confirmation-prompt/component.tsx
  app/components/confirmation-prompt/index.ts
  app/components/confirmation-prompt/types.ts
  app/components/icon/index.ts
  app/components/modal/component.stories.tsx
  app/components/modal/component.tsx
  app/components/modal/index.ts
  app/components/modal/types.ts
  app/package.json
  app/pages/_app.tsx
  app/svgs/ui/map-warning.svg
  app/yarn.lock
Labels: Frontend, New feature, Ready to review

#82 User dropdown
  app/components/tooltip/component.stories.tsx
  app/components/tooltip/component.tsx
  app/layout/header/title/component.tsx
  app/layout/header/user/component.tsx
  app/layout/projects/list/component.tsx
  app/svgs/ui/sign-out.svg
Labels: Frontend, New feature, Ready to review

#74 Export a dump from the dbs and generate a small data extraction centered in the okavango
  Makefile
  api/test/fixtures/features/iucn_acinonyxjubatus.sql
  api/test/fixtures/features/iucn_anomalurusderbianus.sql
  api/test/fixtures/features/iucn_antidorcasmarsupialis.sql
  api/test/fixtures/features/iucn_aonyxcapensis.sql
  api/test/fixtures/features/iucn_crocidurahirta.sql
  api/test/fixtures/features/iucn_dendrohyraxarboreus.sql
  api/test/fixtures/features/iucn_epomophoruswahlbergi.sql
  api/test/fixtures/features/iucn_otolemurcrassicaudatus.sql
  api/test/fixtures/features/iucn_pantherapardus.sql
  api/test/fixtures/test-admin-data.sql
  api/test/fixtures/test-features.sql
  api/test/fixtures/test-geometry.json
  api/test/fixtures/test-wdpa-data.sql
  data/Makefile
  data/data_download/gadm_3.6/Makefile
  data/data_download/wdpa/Makefile
  data/data_restore/.dockerignore
  data/data_restore/Dockerfile
  data/data_restore/Makefile
  data/docker-compose-data_management.yml
  data/docker-compose.yml
  data/notebooks/Lab/convert_csv_sql.ipynb
  data/notebooks/requirements.txt
  geoprocessing/src/migrations/geoprocessing/1611221157285-initialGeoDBSetup.ts
Labels: API, Data, Ready to review

#75 Session workflow improvements
  api/src/modules/users/users.service.ts
  app/auth/cookies.ts
  app/auth/index.ts
  app/auth/strategies/local.ts
  app/hooks/auth/auth.d.ts
  app/hooks/authentication/index.tsx
  app/hooks/authentication/types.ts
  app/hooks/projects/index.ts
  app/hooks/scenarios/index.ts
  app/layout/header/component.tsx
  app/layout/header/user/component.tsx
  app/layout/projects/welcome/component.tsx
  app/layout/protected/component.tsx
  app/layout/sign-in/component.tsx
  app/layout/sign-up/component.tsx
  app/package.json
  app/pages/_app.tsx
  app/pages/api/auth/[...nextauth].ts
  app/pages/api/me.ts
  app/pages/api/sign-in.ts
  app/pages/api/sign-out.ts
  app/pages/api/sign-up.ts
  app/pages/auth/sign-in.tsx
  app/pages/auth/sign-up.tsx
  app/yarn.lock
Labels: API, Frontend, Ready to review

#89 Redirect to referral URL after login
  app/hooks/auth/index.ts
  app/layout/protected/component.tsx
  app/layout/sign-in/component.tsx
  app/layout/sign-up/component.tsx
  app/pages/api/auth/[...nextauth].ts
Labels: Frontend, Ready to review

#90 Feature/refresh token
  app/layout/protected/component.tsx
  app/pages/api/auth/[...nextauth].ts
  app/services/local/index.ts
  app/services/projects/index.ts
  app/services/scenarios/index.ts
  app/services/users/index.ts
  app/utils/use-interval.js
Labels: Frontend, Ready to review

#94 Projects: item navigation [MARXAN-200]
  app/components/projects/item/component.tsx
  app/hooks/projects/index.ts
  app/svgs/ui/arrow-right-2.svg
Labels: Frontend, New feature, Ready to review

#96 Feature/project item delete [MARXAN-101]
  app/components/confirmation-prompt/component.stories.tsx
  app/components/confirmation-prompt/component.tsx
  app/components/modal/component.tsx
  app/components/projects/item/component.stories.tsx
  app/components/projects/item/component.tsx
  app/hooks/projects/index.ts
  app/hooks/projects/types.ts
  app/hooks/scenarios/index.ts
  app/hooks/scenarios/types.ts
  app/layout/header/title/component.tsx
  app/layout/projects/list/component.tsx
  app/layout/projects/toolbar/component.tsx
  app/layout/projects/welcome/component.tsx
  app/layout/scenarios/sidebar/name/component.tsx
  app/package.json
  app/svgs/notifications/delete-warning.svg
  app/svgs/notifications/map-warning.svg
  app/yarn.lock
Labels: Frontend, New feature, Ready to review

#62 Feature/new project
  app/components/button/component.tsx
  app/components/countries/country-region-selector/component.tsx
  app/components/countries/country-region-selector/index.ts
  app/components/countries/country-region-selector/types.ts
  app/components/forms/field/component.tsx
  app/components/projects/planning-unit-area-size/component.tsx
  app/components/projects/planning-unit-area-size/index.ts
  app/components/projects/planning-unit-area-size/types.ts
  app/components/projects/planning-unit-grid/component.tsx
  app/components/projects/planning-unit-grid/index.ts
  app/components/projects/planning-unit-grid/planning-unit-button/component.tsx
  app/components/projects/planning-unit-grid/planning-unit-button/index.ts
  app/components/projects/planning-unit-grid/planning-unit-button/types.ts
  app/components/projects/planning-unit-grid/types.ts
  app/hooks/administrative-areas/index.ts
  app/hooks/administrative-areas/types.ts
  app/hooks/countries/index.ts
  app/hooks/countries/types.ts
  app/hooks/projects/index.ts
  app/hooks/projects/types.ts
  app/hooks/scenarios/types.ts
  app/layout/projects/form/component.tsx
  app/layout/projects/form/constants.ts
  app/layout/projects/form/index.ts
  app/layout/projects/form/planning-area-selector/component.tsx
  app/layout/projects/form/planning-area-selector/index.ts
  app/layout/projects/form/planning-area-selector/types.ts
  app/layout/projects/form/types.ts
  app/layout/projects/map/component.tsx
  app/layout/projects/map/index.ts
  app/layout/projects/map/types.ts
  app/pages/projects/new.tsx
  app/services/administrative-areas/index.ts
  app/services/countries/index.ts
  app/svgs/project/hexagon-selected.svg
  app/svgs/project/hexagon.svg
  app/svgs/project/info.svg
  app/svgs/project/square-selected.svg
  app/svgs/project/square.svg
  app/svgs/project/upload-selected.svg
  app/svgs/project/upload.svg
  app/svgs/ui/upload.svg
  app/types/api-model.ts
  app/types/country-model.ts
  app/types/project-model.ts
Labels: Frontend, New feature, Ready to review

#98 Fix accessibility issues with the Select component
  app/components/forms/select/menu/component.tsx
  app/components/forms/select/multi/component.tsx
  app/components/forms/select/single/component.tsx
  app/components/forms/select/types.d.ts
Labels: Frontend, Ready to review, bug

#87 Feature/data/output models
  data/notebooks/Lab/BLM.ipynb
  data/notebooks/Lab/marxan_BC_example.ipynb
  data/notebooks/Lab/marxan_outputs.ipynb
  data/notebooks/Lab/marxan_utils.ipynb
  data/notebooks/Lab/run_marxan.ipynb
Labels: Data, Ready to review

#97 ADR: queues [MARXAN-204]
  docs/adr/0001_queues.md
Labels: documentation

#104 Project show: scenario type modal
  app/components/icon/component.tsx
  app/components/modal/component.tsx
  app/layout/projects/show/scenarios/component.tsx
  app/layout/projects/show/scenarios/scenario-type/component.tsx
  app/layout/projects/show/scenarios/scenario-type/index.ts
  app/svgs/scenario-types/marxan-with-connectivity.svg
  app/svgs/scenario-types/marxan-with-zones.svg
  app/svgs/scenario-types/marxan.svg
Labels: Frontend, New feature, Ready to review
