Repository Vizzuality/marxan-cloud, pull requests merged in 2021-04, with the labels that each got.

#117 Scenarios: Protected areas [MARXAN-329]
  app/components/forms/select/single/component.tsx
  app/hooks/wdpa/index.ts
  app/layout/scenarios/sidebar/wdpa/categories/component.tsx
  app/layout/scenarios/sidebar/wdpa/component.tsx
  app/layout/scenarios/sidebar/wdpa/threshold/component.tsx
  app/services/wdpa/index.ts
Labels: Frontend, New feature, Ready to review

#88 PU grids generation.
  Makefile
  api/CHANGELOG.md
  api/config/custom-environment-variables.json
  api/config/default.json
  api/package.json
  api/src/app.module.ts
  api/src/modules/planning-units/dto/create.planning-units.dto.ts
  api/src/modules/planning-units/dto/update.planning-units.dto.ts
  api/src/modules/planning-units/planning-units.module.ts
  api/src/modules/planning-units/planning-units.service.ts
  api/src/modules/projects/dto/create.project.dto.ts
  api/src/modules/projects/projects.module.ts
  api/src/modules/projects/projects.service.ts
  api/test/e2e.config.ts
  api/test/planning-units.e2e-spec.ts
  api/yarn.lock
  data/notebooks/Lab/pu_creation_logic.ipynb
  data/notebooks/Lab/run_marxan.ipynb
  docker-compose-test-e2e.ci.yml
  docker-compose-test-e2e.local.yml
  docker-compose-test-e2e.yml
  docker-compose.yml
  env.default
  geoprocessing/CHANGELOG.md
  geoprocessing/config/default.json
  geoprocessing/ormconfig.ts
  geoprocessing/package.json
  geoprocessing/src/app.module.ts
  geoprocessing/src/migrations/geoprocessing/1614256630000-AddCountriesView.ts
  geoprocessing/src/migrations/geoprocessing/1616690947000-AddIdToCountriesView.ts
  geoprocessing/src/modules/planning-units/dto/create.regular.planning-units.dto.ts
  geoprocessing/src/modules/planning-units/planning-units.job.ts
  geoprocessing/src/modules/planning-units/planning-units.module.ts
  geoprocessing/src/modules/planning-units/planning-units.worker.ts
  geoprocessing/src/ormconfig.ts
  geoprocessing/test/app.e2e-spec.ts
  geoprocessing/test/e2e.config.ts
  geoprocessing/test/jest-e2e.json
  geoprocessing/test/planning-units-processor.e2e-spec.ts
  geoprocessing/yarn.lock
  postgresql/Dockerfile
Labels: API, Data, New feature, Ready to review

#120 ammend problem with seed geodb
  Makefile
  README.md
  data/data_download/iucn/Makefile
  data/data_restore/Makefile
  data/docker-compose-data_management.yml
  data/docker-compose.yml
Labels: Data, Ready to review, bug

#119 Scenario settings [MARXAN-331]
  app/components/scenarios/item/component.tsx
  app/components/scenarios/item/settings/component.tsx
  app/components/scenarios/item/settings/index.ts
  app/layout/projects/show/scenarios/component.tsx
  app/layout/projects/show/scenarios/settings/component.tsx
  app/layout/projects/show/scenarios/settings/index.ts
  app/layout/projects/show/scenarios/toolbar/component.tsx
  app/pages/projects/[pid]/index.tsx
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
  app/pages/projects/[pid]/scenarios/new.tsx
Labels: Frontend, New feature, Ready to review

#121 Scenario tabs
  app/layout/projects/new/form/component.tsx
  app/layout/projects/show/scenarios/component.tsx
  app/layout/scenarios/sidebar/component.tsx
  app/layout/scenarios/sidebar/tabs/component.tsx
  app/layout/scenarios/sidebar/tabs/index.ts
  app/layout/scenarios/sidebar/wdpa/component.tsx
  app/store/index.ts
  app/store/slices/scenarios/edit.ts
  app/tailwind.config.js
Labels: Frontend, New feature, Ready to review

#127 Remove duplicate env var
  env.default
Labels: documentation

#123 GeoFeaturesModule [MARXAN-155]
  api/package.json
  api/src/app.module.ts
  api/src/migrations/api/1618241224000-AddDraftStatusToJobStatusEnum.ts
  api/src/migrations/api/1618248224000-AllowToLinkCustomGeoFeaturesToProjects.ts
  api/src/modules/geo-features/dto/create.geo-feature.dto.ts
  api/src/modules/geo-features/dto/update.geo-feature.dto.ts
  api/src/modules/geo-features/geo-feature.api.entity.ts
  api/src/modules/geo-features/geo-feature.geo.entity.ts
  api/src/modules/geo-features/geo-features.controller.ts
  api/src/modules/geo-features/geo-features.module.ts
  api/src/modules/geo-features/geo-features.service.ts
  api/src/modules/projects/projects.controller.ts
  api/src/modules/projects/projects.module.ts
  api/src/modules/projects/projects.service.ts
  api/src/types/resource.interface.ts
  api/test/fixtures/features/iucn_acinonyxjubatus.sql
  api/test/fixtures/features/iucn_anomalurusderbianus.sql
  api/test/fixtures/features/iucn_antidorcasmarsupialis.sql
  api/test/fixtures/features/iucn_aonyxcapensis.sql
  api/test/fixtures/features/iucn_crocidurahirta.sql
  api/test/fixtures/features/iucn_dendrohyraxarboreus.sql
  api/test/fixtures/features/iucn_epomophoruswahlbergi.sql
  api/test/fixtures/features/iucn_otolemurcrassicaudatus.sql
  api/test/fixtures/features/iucn_pantherapardus.sql
  api/test/geo-features.e2e-spec.ts
  api/test/protected-areas.e2e-spec.ts
  api/yarn.lock
  data/data_download/iucn/Makefile
  data/data_download/world_terrestrial_ecosystems/Makefile
  data/notebooks/Lab/convert_csv_sql.ipynb
  data/notebooks/Lab/run_marxan.ipynb
  geoprocessing/src/migrations/geoprocessing/1618853324000-ExtractDistictPropsFromFeatures.ts
Labels: API

#134 fix yaml :facepalm:
  docker-compose-test-e2e.ci.yml
Labels: API

#138 set sensible (for now) timeout for API CI jobs
  .github/workflows/api-e2e-tests.yml
Labels: bug, infrastructure

#140 use mockReturnThis() for convenience
  api/src/filters/all-exceptions.exception.filter.spec.ts
Labels: API, bug

#141 fix missing meta prop for pagination
  api/src/utils/app-base.service.ts
Labels: API, bug

#124 feature flow prototyping
  Makefile
  api/test/fixtures/test-data.sql
  api/test/fixtures/test-features.sql
  api/test/fixtures/test-geodata.sql
  data/notebooks/Lab/costSurfaceInitial_logic.ipynb
  data/notebooks/Lab/datfilesCreationFromDB_logic.ipynb
  data/notebooks/Lab/featuresForScenario_logic.ipynb
  data/notebooks/Lab/lockIn_out_logic.ipynb
  data/notebooks/Lab/marxan_utils.ipynb
  data/notebooks/Lab/pu_paIntersectionForScenario_logic.ipynb
  data/notebooks/Lab/run_marxan.ipynb
  geoprocessing/src/migrations/geoprocessing/1611221157285-InitialGeoDBSetup.ts
Labels: API, Data, Ready to review

#145 Meta inside service responses. Features pagination. Features loaders
  app/components/search/component.tsx
  app/hooks/administrative-areas/index.ts
  app/hooks/countries/index.ts
  app/hooks/features/index.ts
  app/hooks/me/index.ts
  app/hooks/projects/index.ts
  app/hooks/scenarios/index.ts
  app/hooks/wdpa/index.ts
  app/layout/header/title/component.tsx
  app/layout/projects/new/form/component.tsx
  app/layout/scenarios/sidebar/features/add/list/component.tsx
  app/layout/scenarios/sidebar/features/intersect/component.tsx
  app/layout/scenarios/sidebar/features/intersect/list/component.tsx
  app/layout/scenarios/sidebar/name/component.tsx
  app/package.json
  app/pages/auth/sign-up.tsx
  app/services/administrative-areas/index.ts
  app/services/countries/index.ts
  app/services/projects/index.ts
  app/services/scenarios/index.ts
  app/services/users/index.ts
  app/services/wdpa/index.ts
  app/yarn.lock
Labels: Frontend, New feature, Ready to review
