Repository Vizzuality/marxan-cloud, pull requests merged in 2021-12, with the labels that each got.

#659 test: adds fixtures, improvements in project-acl e2e tests
  api/apps/api/test/access-control/project-acl-delete.e2e-spec.ts
  api/apps/api/test/access-control/project-acl-get.e2e-spec.ts
  api/apps/api/test/access-control/project-acl-patch.e2e-spec.ts
  api/apps/api/test/access-control/project-acl.fixtures.ts
  api/apps/api/test/fixtures/test-data.sql
  api/apps/api/test/utils/projects-acl.test.utils.ts
Labels: API

#662 fix(front): cost surface layer show mode[MARXAN-1073]
  app/layout/scenarios/show/map/component.tsx
Labels: bug, Frontend, WIP

#685 fix(front): update solutions table[MARXAN-1094]
  app/components/table/component.tsx
Labels: bug, Frontend

#717 Feat(front): features landing page section
  app/images/home-carousel/bg-image.jpg
  app/images/home-carousel/carousel_01.png
  app/images/home-carousel/carousel_02.png
  app/images/home-carousel/carousel_03.png
  app/images/home-carousel/carousel_04.png
  app/images/home-features/project-features.png
  app/layout/home/carousel-section/component.tsx
  app/layout/home/carousel-section/constants.ts
  app/layout/home/carousel-section/index.ts
  app/layout/home/features/component.tsx
  app/layout/home/features/constants.ts
  app/layout/partners/component.tsx
  app/pages/index.tsx
  app/svgs/home/analyze-report.svg
  app/svgs/home/cloud-storage.svg
  app/svgs/home/collaborate.svg
  app/svgs/home/download-analysis.svg
  app/svgs/home/improve-efficiency.svg
Labels: Frontend, Ready to review

#710 Feat(front): banner flow section[MARXAN-1137]
  app/images/home-banner/banner-1.png
  app/images/home-banner/banner-2.png
  app/images/home-banner/banner-3.png
  app/images/home-banner/banner-background.png
  app/layout/home/banner/component.tsx
  app/layout/home/banner/index.ts
  app/package.json
  app/pages/index.tsx
  app/pages/partners.tsx
  app/tailwind.config.js
  app/yarn.lock
Labels: Frontend, WIP, Ready to review

#692 Fixing scenario features list update loop
  app/layout/scenarios/edit/features/add/component.tsx
  app/layout/scenarios/edit/features/component.tsx
  app/layout/scenarios/edit/features/list/component.tsx
Labels: bug, Frontend, Ready to review

#693 Show custom features in the add modal on top
  app/hooks/features/index.ts
  app/layout/scenarios/edit/features/add/list/component.tsx
  app/tailwind.config.js
Labels: enhancement, Frontend, Ready to review

#718 Home hero/intro section
  app/images/home-hero/bg-01.png
  app/images/home-hero/bg-02.png
  app/images/home-hero/bg-03.png
  app/images/home-hero/bg-04.png
  app/images/home-hero/hero-image-1.png
  app/images/home-hero/image-01.jpg
  app/images/home-hero/image-02.jpg
  app/images/home-hero/image-03.jpg
  app/layout/header/component.tsx
  app/layout/home/features/component.tsx
  app/layout/home/hero/component.tsx
  app/layout/home/hero/hero-animation/component.tsx
  app/layout/home/hero/hero-animation/constants.ts
  app/layout/home/hero/hero-animation/index.ts
  app/pages/index.tsx
Labels: Frontend, WIP

#698 feat(front): landing page redesign[MARXAN-1132]
  app/images/home-banner/banner-1.png
  app/images/home-banner/banner-2.png
  app/images/home-banner/banner-3.png
  app/images/home-banner/banner-background.png
  app/images/home-carousel/bg-image.jpg
  app/images/home-carousel/carousel_01.png
  app/images/home-carousel/carousel_02.png
  app/images/home-carousel/carousel_03.png
  app/images/home-carousel/carousel_04.png
  app/images/home-features/example-placeholder.png
  app/images/home-features/example-project.png
  app/images/home-hero/hero-image-1.png
  app/images/home-intro/bg-01.png
  app/images/home-intro/bg-02.png
  app/images/home-intro/bg-03.png
  app/images/home-intro/bg-04.png
  app/images/home-intro/image-01.jpg
  app/images/home-intro/image-02.jpg
  app/images/home-intro/image-03.jpg
  app/images/partners/biopama_logo.png
  app/images/partners/european-commission_logo.png
  app/images/partners/mapbox_logo.png
  app/images/partners/microsoft_logo.png
  app/images/partners/pacmara_logo.png
  app/images/partners/the-nature-conservancy_logo.png
  app/images/partners/un-environment_logo.png
  app/images/partners/university-queensland_logo.png
  app/images/partners/vizzuality_logo.png
  app/layout/header/component.tsx
  app/layout/home/banner/component.tsx
  app/layout/home/banner/index.ts
  app/layout/home/carousel-section/component.tsx
  app/layout/home/carousel-section/constants.ts
  app/layout/home/features/component.tsx
  app/layout/home/features/constants.ts
  app/layout/home/hero/component.tsx
  app/layout/home/intro/component.tsx
  app/layout/home/intro/index.ts
  app/layout/home/intro/intro-animation/component.tsx
  app/layout/home/intro/intro-animation/constants.ts
  app/layout/home/intro/intro-animation/index.ts
  app/layout/home/partners/component.tsx
  app/layout/home/partners/constants.ts
  app/layout/home/partners/index.ts
  app/layout/partners/component.tsx
  app/layout/partners/constants.ts
  app/package.json
  app/pages/index.tsx
  app/pages/partners.tsx
  app/svgs/home/analyze-report.svg
  app/svgs/home/cloud-storage.svg
  app/svgs/home/collaborate.svg
  app/svgs/home/download-analysis.svg
  app/svgs/home/improve-efficiency.svg
  app/tailwind.config.js
  app/yarn.lock
Labels: Frontend, WIP, New feature
