Repository Vizzuality/marxan-cloud, pull requests merged in 2021-08, with the labels that each got.

#385 front(fix): published projects planning area + contributors [MARXAN-604]
  app/components/projects/published-item/component.tsx
  app/hooks/projects/index.ts
  app/layout/community/published-projects/component.tsx
Labels: Frontend, Ready to review, bug

#376 Analysis: persists inclusion exclusion
  app/hooks/map/index.ts
  app/hooks/scenarios/index.ts
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/clicking/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/tabs/component.tsx
  app/store/slices/scenarios/edit.ts
Labels: Frontend, New feature, WIP

#392 front: add number of features to scenario settings [MARXAN-600]
  app/layout/projects/show/scenarios/settings/component.tsx
Labels: Frontend, Ready to review

#391 Landing page redesign
  app/components/button/component.tsx
  app/components/carousel/component.tsx
  app/images/home-carousel/bg-image.jpg
  app/images/home-hero/hero-image-1.png
  app/layout/footer/component.tsx
  app/layout/header/component.tsx
  app/layout/header/user/component.tsx
  app/layout/home/carousel-section/component.tsx
  app/layout/home/features/component.tsx
  app/layout/home/features/constants.ts
  app/layout/home/hero/component.tsx
  app/layout/partners/component.tsx
  app/layout/statics/button-link/component.tsx
  app/pages/index.tsx
  app/svgs/logo-black.svg
  app/tailwind.config.js
Labels: Frontend, WIP

#400 front: add data on upload shapefile when create project [MARXAN-542]
  app/layout/projects/new/form/planning-area-uploader/component.tsx
Labels: Frontend, Ready to review

#394 About page redesign
  app/images/about/bg-utilities.jpg
  app/images/about/utilities-1.png
  app/layout/about/utilities/component.tsx
  app/layout/about/values/component.tsx
  app/layout/statics/column/component.tsx
  app/layout/statics/hero/component.tsx
  app/pages/about.tsx
Labels: Frontend, WIP

#395 Improve Buttons design
  app/components/button/component.tsx
  app/layout/header/component.tsx
  app/layout/home/hero/component.tsx
Labels: Frontend, WIP

#399 Vector layers for features and outputs PUs
  api/apps/api/src/modules/scenarios/dto/scenario-metadata.dto.ts
  api/apps/api/src/modules/scenarios/scenario.api.entity.ts
  api/apps/api/src/modules/scenarios/scenarios.controller.ts
  api/apps/api/test/fixtures/test-geodata.sql
  api/apps/api/test/proxy.vector-tiles.e2e-spec.ts
  api/apps/geoprocessing/src/migrations/geoprocessing/1627652172613-ScenarioPuFeaturesForTilesView.ts
  api/apps/geoprocessing/src/modules/scenarios/scenarios.controller.ts
  api/apps/geoprocessing/src/modules/scenarios/scenarios.service.ts
  api/apps/geoprocessing/src/modules/tile/tile.service.ts
  api/apps/geoprocessing/test/index.html
  api/libs/scenarios-planning-unit/src/scenarios-pu-cost-data.geo.entity.ts
  api/libs/scenarios-planning-unit/src/scenarios-pu-output.geo.entity.ts
  api/libs/scenarios-planning-unit/src/scenarios-pu-pa-data.geo.entity.ts
  docs/adr/0005_outputs.md
Labels: API, Ready to review

#398 Community page redesign
  app/components/button/component.tsx
  app/components/icon/component.tsx
  app/images/community/info-bg.jpg
  app/layout/community/component.tsx
  app/layout/community/published-projects/component.tsx
  app/layout/community/published-projects/detail/component.tsx
  app/layout/community/published-projects/detail/share/component.tsx
  app/layout/community/published-projects/duplicate-button/component.tsx
  app/layout/header/component.tsx
  app/layout/statics/backlink/component.tsx
  app/layout/statics/button-link/component.tsx
  app/layout/statics/column/component.tsx
  app/pages/community/index.tsx
  app/pages/community/projects/[pid]/index.tsx
  app/pages/community/projects/index.tsx
  app/svgs/social/link.svg
Labels: Frontend, Ready to review

#378 Feat(front): solutions details [MARXAN-606]
  app/components/features/selected-item/component.tsx
  app/components/map/legend/component.stories.tsx
  app/components/map/legend/types/gradient/component.tsx
  app/components/table/component.tsx
  app/hooks/scenarios/index.ts
  app/hooks/solutions/index.ts
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/map/drawing-manager/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/clicking/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/drawing/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/uploading/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/component.tsx
  app/layout/scenarios/sidebar/analysis/component.tsx
  app/layout/scenarios/sidebar/analysis/cost-surface/component.tsx
  app/layout/scenarios/sidebar/analysis/sections/component.tsx
  app/layout/scenarios/sidebar/analysis/sections/item/component.tsx
  app/layout/scenarios/sidebar/features/component.tsx
  app/layout/scenarios/sidebar/features/list/component.tsx
  app/layout/scenarios/sidebar/features/targets/component.tsx
  app/layout/scenarios/sidebar/solutions/component.tsx
  app/layout/scenarios/sidebar/solutions/details/component.tsx
  app/layout/scenarios/sidebar/solutions/details/types.ts
  app/layout/scenarios/sidebar/solutions/sections/constants.ts
  app/layout/scenarios/sidebar/solutions/table-form/component.tsx
  app/layout/scenarios/sidebar/solutions/table-form/types.ts
  app/layout/scenarios/sidebar/solutions/table/cells/best/component.tsx
  app/layout/scenarios/sidebar/solutions/table/cells/best/types.ts
  app/layout/scenarios/sidebar/solutions/table/component.tsx
  app/layout/scenarios/sidebar/solutions/table/types.ts
  app/layout/scenarios/sidebar/solutions/types.ts
  app/layout/scenarios/sidebar/tabs/component.tsx
  app/layout/scenarios/sidebar/wdpa/categories/component.tsx
  app/layout/scenarios/sidebar/wdpa/component.tsx
  app/layout/scenarios/sidebar/wdpa/threshold/component.tsx
  app/layout/solutions/frequency/component.tsx
  app/layout/solutions/frequency/index.ts
  app/layout/solutions/selected/component.tsx
  app/layout/solutions/selected/index.ts
  app/pages/projects/[pid]/scenarios/[sid]/index.tsx
  app/store/index.ts
  app/store/slices/scenarios/detail.ts
  app/store/slices/scenarios/edit.ts
Labels: Frontend, New feature, Ready to review

#393 PU grid
  app/.nvmrc
  app/components/features/selected-item/component.tsx
  app/hooks/administrative-areas/index.ts
  app/hooks/countries/index.ts
  app/hooks/features/index.ts
  app/hooks/gap-analysis/index.ts
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/hooks/me/index.ts
  app/hooks/organizations/index.ts
  app/hooks/projects/index.ts
  app/hooks/scroll/index.ts
  app/hooks/toast/index.tsx
  app/hooks/wdpa/index.ts
  app/layout/community/published-projects/duplicate-button/component.tsx
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/clicking/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/drawing/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/uploading/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/component.tsx
  app/layout/scenarios/sidebar/analysis/component.tsx
  app/layout/scenarios/sidebar/analysis/cost-surface/component.tsx
  app/layout/scenarios/sidebar/features/component.tsx
  app/layout/scenarios/sidebar/features/list/component.tsx
  app/layout/scenarios/sidebar/tabs/component.tsx
  app/layout/scenarios/sidebar/tabs/constants.ts
  app/layout/scenarios/sidebar/types.ts
  app/layout/scenarios/sidebar/wdpa/component.tsx
  app/layout/scenarios/sidebar/wdpa/threshold/component.tsx
  app/store/index.ts
  app/store/slices/scenarios/edit.ts
Labels: Frontend, New feature, WIP

#402 Front(feat): analytics settings [MARXAN-608]
  app/components/features/selected-item/component.tsx
  app/components/projects/item/component.tsx
  app/layout/head/component.tsx
  app/layout/head/index.ts
  app/layout/projects/new/form/component.tsx
  app/layout/projects/show/header/toolbar/component.tsx
  app/layout/scenarios/sidebar/analysis/cost-surface/component.tsx
  app/layout/scenarios/sidebar/analysis/sections/component.tsx
  app/layout/scenarios/sidebar/analysis/sections/item/component.tsx
  app/layout/scenarios/sidebar/features/targets/component.tsx
  app/layout/scenarios/sidebar/name/component.tsx
  app/layout/scenarios/sidebar/run/component.tsx
  app/layout/scenarios/sidebar/solutions/details/types.ts
  app/layout/scenarios/sidebar/wdpa/categories/component.tsx
  app/layout/scenarios/sidebar/wdpa/threshold/component.tsx
  app/layout/sign-up/component.tsx
  app/layout/title/scenario-title/component.tsx
  app/package.json
  app/pages/404.tsx
  app/pages/_app.tsx
  app/pages/_document.tsx
  app/pages/about.tsx
  app/pages/auth/forgot-password.tsx
  app/pages/auth/sign-in.tsx
  app/pages/auth/sign-up.tsx
  app/pages/community/index.tsx
  app/pages/community/projects/index.tsx
  app/pages/index.tsx
  app/pages/me.tsx
  app/pages/partners.tsx
  app/pages/privacy-policy.tsx
  app/pages/terms-of-use.tsx
  app/yarn.lock
Labels: Frontend, New feature, Ready to review

#425 Legend
  app/components/features/selected-item/component.tsx
  app/components/map/legend/component.stories.tsx
  app/components/map/legend/component.tsx
  app/components/map/legend/item/component.tsx
  app/hooks/map/constants.tsx
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/sidebar/solutions/details/component.tsx
  app/svgs/map/hexagon.svg
  app/svgs/map/square.svg
Labels: Frontend, Ready to review, New feature

#427 front(fix): enable get features
  app/hooks/features/index.ts
Labels: bug, Frontend, Ready to review

#405 Feature/data/rearrange data for demos
  Makefile
  api/apps/api/src/modules/geo-features/geo-features.service.ts
  api/apps/api/src/modules/projects/projects-crud.service.ts
  api/apps/api/src/modules/protected-areas/protected-areas.controller.ts
  api/apps/api/src/modules/protected-areas/protected-areas.service.ts
  api/apps/api/test/fixtures/test-data.sql
  api/apps/api/test/fixtures/test-geometry-demo-australia.json
  api/apps/api/test/fixtures/test-geometry-demo-brazil.json
  api/apps/api/test/fixtures/test-geometry-demo-okavango.json
  api/apps/api/test/fixtures/test-geometry-subset.json
  api/apps/api/test/fixtures/test-init-apidb.sql
  api/apps/geoprocessing/src/modules/features/features.geo.entity.ts
  api/apps/geoprocessing/src/modules/features/features.service.ts
  api/apps/geoprocessing/src/modules/planning-units/dto/create.regular.planning-units.dto.ts
  api/apps/geoprocessing/src/modules/planning-units/planning-units.job.ts
  api/apps/geoprocessing/src/modules/planning-units/planning-units.worker.ts
  api/apps/geoprocessing/test/index.html
  api/libs/planning-area-repository/src/custom-planning-area.repository.ts
  data/bots/README.md
  data/bots/demo-australia/bot.ts
  data/bots/demo-australia/kimberley.zip
  data/bots/demo-brazil/bot.ts
  data/bots/demo-brazil/test_mata.zip
  data/bots/demo-okavango/bot.ts
  data/bots/demo-okavango/planning-area.zip
  data/bots/scenario-hero/bot.ts
  data/data_download/Makefile
  data/data_download/demo_data_features_bioregion/Makefile
  data/data_download/demo_data_features_species/Makefile
  data/data_download/gadm_3.6/Makefile
  data/data_download/wdpa/Makefile
  data/data_download/world_terrestrial_ecosystems/Makefile
  data/docker-compose-data_management.yml
Labels: Data, WIP

#411 Front(feat): tabs dependency [MARXAN-601]
  app/components/tabs/component.tsx
  app/hooks/features/index.ts
  app/hooks/scenarios/index.ts
  app/layout/header/title/component.tsx
  app/layout/meta-icons/component.tsx
  app/layout/scenarios/sidebar/analysis/component.tsx
  app/layout/scenarios/sidebar/features/component.tsx
  app/layout/scenarios/sidebar/features/intersect/component.tsx
  app/layout/scenarios/sidebar/name/component.tsx
  app/layout/scenarios/sidebar/run/component.tsx
  app/layout/scenarios/sidebar/solutions/component.tsx
  app/layout/scenarios/sidebar/tabs/component.tsx
  app/layout/scenarios/sidebar/types.ts
  app/layout/scenarios/sidebar/wdpa/categories/component.tsx
  app/layout/scenarios/sidebar/wdpa/component.tsx
  app/layout/scenarios/sidebar/wdpa/threshold/component.tsx
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
  app/utils/utils-scenarios.js
Labels: Frontend, Ready to review, New feature

#424 Feat(front): solutions updates [MARXAN-664]
  app/components/scenarios/blm-chart/component.tsx
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/layout/header/title/component.tsx
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/edit/run/chart/constants.ts
  app/layout/scenarios/edit/solutions/details/component.tsx
  app/layout/scenarios/edit/solutions/table-form/component.tsx
  app/layout/scenarios/show/map/component.tsx
  app/pages/projects/[pid]/scenarios/new.tsx
  app/public/images/solutions/solution-less-blm.png
  app/public/images/solutions/solution-medium-blm.png
  app/public/images/solutions/solution-more-blm.png
Labels: bug, Frontend, Ready to review, New feature

#444 Project map
  app/components/scenarios/item/component.tsx
  app/hooks/scenarios/index.ts
  app/layout/projects/show/map/component.tsx
  app/layout/projects/show/scenarios/component.tsx
Labels: Frontend, Ready to review, New feature

#450 Front(fix): best-solution [MARXAN-666][MARXAN-650]
  app/hooks/gap-analysis/index.ts
  app/hooks/solutions/index.ts
  app/layout/scenarios/edit/analysis/gap-analysis/list/component.tsx
  app/layout/scenarios/edit/features/component.tsx
  app/layout/scenarios/edit/run/component.tsx
  app/layout/scenarios/edit/tabs/constants.ts
  app/layout/scenarios/show/analysis/adjust-planning-units/component.tsx
  app/layout/scenarios/show/analysis/cost-surface/component.tsx
  app/layout/scenarios/show/analysis/gap-analysis/list/component.tsx
  app/layout/scenarios/show/solutions/details/component.tsx
  app/layout/scenarios/show/solutions/table-form/component.tsx
  app/layout/scenarios/show/solutions/table-form/types.ts
  app/public/styles/tailwind.storybook.css
  app/utils/utils-scenarios.js
Labels: bug, Frontend, Ready to review

#462 Bots: improvements
  data/bots/demo-australia/bot.ts
  data/bots/demo-brazil/bot.ts
  data/bots/demo-okavango/bot.ts
Labels: enhancement, API, Data, Ready to review

#461 Front(feat):opacity manager [MARXAN-680][MARXAN-682]
  app/components/forms/slider/component.stories.tsx
  app/components/forms/slider/component.tsx
  app/components/forms/slider/thumb/component.tsx
  app/components/map/legend/item/component.tsx
  app/components/map/legend/types/basic/component.tsx
  app/components/projects/item/component.tsx
  app/components/projects/published-item/component.tsx
  app/hooks/map/constants.tsx
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/layout/community/published-projects/component.tsx
  app/layout/community/published-projects/detail/component.tsx
  app/layout/header/user/component.tsx
  app/layout/projects/show/header/component.tsx
  app/layout/projects/show/header/contributors/component.tsx
  app/layout/projects/show/map/component.tsx
  app/layout/projects/show/scenarios/settings/component.tsx
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/edit/run/component.tsx
  app/layout/scenarios/edit/status/component.tsx
  app/layout/scenarios/show/map/component.tsx
  app/layout/scenarios/show/solutions/component.tsx
  app/layout/scenarios/show/solutions/details/component.tsx
  app/layout/scenarios/show/solutions/table/component.tsx
  app/store/slices/scenarios/detail.ts
  app/store/slices/scenarios/edit.ts
  app/svgs/map/opacity.svg
Labels: bug, Frontend, WIP, New feature

#467 Project show: layer settings
  app/layout/projects/show/map/component.tsx
  app/store/slices/projects/[id].ts
Labels: Frontend, Ready to review, New feature

#440 Scenario planning units pa area calculations worker
  api/apps/api/src/migrations/api/1627979898685-AddNewProcessingEvents.ts
  api/apps/api/src/migrations/api/1629285532316-AddSubmittedEventToProtectedArea.ts
  api/apps/api/src/migrations/api/1629285535432-DropCascadeOutputs.ts
  api/apps/api/src/migrations/api/1629703588844-AddEventsForSpecification.ts
  api/apps/api/src/modules/planning-units-protection-level/calculate-planning-units-protection-level.command.ts
  api/apps/api/src/modules/planning-units-protection-level/calculate-planning-units-protection-level.handler.ts
  api/apps/api/src/modules/planning-units-protection-level/planning-units-protection-level.module.ts
  api/apps/api/src/modules/projects/job-status/job-status.view.api.entity.ts
  api/apps/api/src/modules/projects/job-status/jobs.enum.ts
  api/apps/api/src/modules/scenario-specification/adapters/scenario-specification-adapters.module.ts
  api/apps/api/src/modules/scenario-specification/adapters/specification-activated.handler.ts
  api/apps/api/src/modules/scenarios-features/copy/copy-query.service.ts
  api/apps/api/src/modules/scenarios-features/scenario-features.service.ts
  api/apps/api/src/modules/scenarios-features/split/split-query.service.ts
  api/apps/api/src/modules/scenarios/__mocks__/input-change.data.ts
  api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units-protection-status-calculator-service.ts
  api/apps/api/src/modules/scenarios/scenario.api.entity.ts
  api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
  api/apps/api/src/modules/scenarios/scenarios.controller.ts
  api/apps/api/src/modules/scenarios/wdpa-area-calculation.service.spec.ts
  api/apps/api/src/modules/scenarios/wdpa-area-calculation.service.ts
  api/apps/api/src/modules/specification/adapters/specification-adapters.module.ts
  api/apps/api/src/modules/specification/adapters/specification-candidate-created.handler.ts
  api/apps/api/src/modules/specification/adapters/specification.repository.ts
  api/apps/api/test/calculate-pu-protection-level/example.integration.e2e-spec.ts
  api/apps/api/test/e2e.config.ts
  api/apps/api/test/jest-e2e.json
  api/apps/api/test/project-scenarios.e2e-spec.ts
  api/apps/api/test/scenarios/input-file.e2e-spec.ts
  api/apps/geoprocessing/src/app.module.ts
  api/apps/geoprocessing/src/migrations/geoprocessing/1628277511111-ChangeLargeDataStorage.ts
  api/apps/geoprocessing/src/migrations/geoprocessing/1628277511112-ChangeViewScenarioPuFeatures.ts
  api/apps/geoprocessing/src/modules/scenario-protected-area-calculation/scenario-protected-area-calculation-processor.ts
  api/apps/geoprocessing/src/modules/scenario-protected-area-calculation/scenario-protected-area-calculation.module.ts
  api/apps/geoprocessing/src/modules/scenario-protected-area-calculation/scenario-protected-area-calculation.worker.ts
  api/apps/geoprocessing/src/modules/scenarios/scenarios.service.ts
  api/apps/geoprocessing/src/modules/tile/tile.service.ts
  api/apps/geoprocessing/test/index.html
  api/apps/geoprocessing/test/jest-e2e.json
  api/libs/api-events/src/api-event-kinds.enum.ts
  api/libs/planning-unit-protection-level/src/index.ts
  api/libs/planning-unit-protection-level/src/job-input.ts
  api/libs/planning-unit-protection-level/src/queue-name.ts
  api/libs/planning-unit-protection-level/tsconfig.lib.json
  api/nest-cli.json
  api/package.json
  api/tsconfig.json
  data/bots/demo-australia/bot.ts
  data/bots/demo-brazil/bot.ts
  data/data_download/Makefile
  data/data_download/demo_data_features_bioregion/Makefile
  data/data_download/demo_data_features_species/Makefile
  docker-compose.yml
Labels: API, WIP

#477 Feat/published project map [MARXAN-683]
  app/components/map/legend/item/component.tsx
  app/components/projects/published-item/component.tsx
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/layout/community/published-projects/detail/component.tsx
  app/layout/community/published-projects/detail/map/component.tsx
  app/layout/projects/show/map/component.tsx
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/show/map/component.tsx
  app/layout/scenarios/show/solutions/details/component.tsx
  app/pages/community/projects/[pid]/index.tsx
Labels: Frontend, Ready to review, New feature

#482 Front(fix): UI hot fixes [MARXAN-689]
  app/components/map/legend/item/component.tsx
  app/components/scenarios/blm-chart/component.tsx
  app/components/table/component.tsx
  app/images/home-carousel/carousel-1.png
  app/images/home-carousel/carousel-2.png
  app/images/home-carousel/carousel-3.png
  app/images/home-carousel/carousel-4.png
  app/images/home-carousel/carousel_01.png
  app/images/home-carousel/carousel_02.png
  app/images/home-carousel/carousel_03.png
  app/images/home-carousel/carousel_04.png
  app/layout/home/carousel-section/constants.ts
  app/layout/home/hero/component.tsx
  app/layout/scenarios/edit/analysis/adjust-planning-units/component.tsx
  app/layout/scenarios/edit/analysis/component.tsx
  app/layout/scenarios/edit/analysis/cost-surface/component.tsx
  app/layout/scenarios/edit/analysis/gap-analysis/component.tsx
  app/layout/scenarios/edit/features/component.tsx
  app/layout/scenarios/show/analysis/adjust-planning-units/component.tsx
  app/layout/scenarios/show/analysis/cost-surface/component.tsx
  app/layout/scenarios/show/analysis/gap-analysis/component.tsx
  app/layout/scenarios/show/solutions/component.tsx
  app/layout/scenarios/show/solutions/details/component.tsx
  app/layout/scenarios/show/solutions/gap-analysis/component.tsx
  app/layout/scenarios/show/solutions/table-form/component.tsx
  app/layout/solutions/frequency/component.tsx
  app/layout/solutions/selected/component.tsx
  app/public/images/solutions/solution-less-blm.png
  app/public/images/solutions/solution-medium-blm.png
  app/public/images/solutions/solution-more-blm.png
Labels: bug, Frontend, Ready to review

#486 Data/fix/improve features performance
  api/apps/geoprocessing/src/migrations/geoprocessing/1629896555555-AddIdexesFeaturesVTiles.ts
  api/apps/geoprocessing/src/modules/features/features.service.ts
  api/apps/geoprocessing/src/modules/scenarios/scenarios.service.ts
  data/data_download/Makefile
  data/data_download/demo_data_features_bioregion/Makefile
  data/data_download/demo_data_features_species/Makefile
  data/data_download/world_terrestrial_ecosystems/Makefile
  docker-compose.yml
Labels: Ready to review

#512 Front(fix) texts and performance
  app/components/forms/select/toggle/component.tsx
  app/components/info-button/component.tsx
  app/components/map/controls/fit-bounds/component.tsx
  app/components/map/controls/zoom/component.tsx
  app/components/map/legend/item/component.tsx
  app/components/search/component.tsx
  app/components/tabs/component.tsx
  app/components/toast/component.tsx
  app/layout/header/component.tsx
  app/layout/header/user/component.tsx
  app/layout/help/beacon/component.tsx
  app/layout/me/profile/avatar/component.tsx
  app/layout/partners/component.tsx
  app/layout/projects/new/form/planning-area-uploader/component.tsx
  app/layout/projects/show/header/contributors/component.tsx
  app/layout/scenarios/edit/analysis/cost-surface/component.tsx
  app/layout/scenarios/edit/analysis/gap-analysis/component.tsx
  app/layout/scenarios/edit/features/component.tsx
  app/layout/scenarios/edit/wdpa/categories/component.tsx
  app/layout/scenarios/show/analysis/gap-analysis/component.tsx
  app/layout/scenarios/show/solutions/details/component.tsx
  app/layout/scenarios/show/solutions/gap-analysis/component.tsx
  app/layout/scenarios/show/solutions/list/component.tsx
  app/layout/scenarios/show/solutions/table-form/component.tsx
  app/layout/sections/item/component.tsx
  app/layout/statics/contact/component.tsx
  app/pages/_document.tsx
Labels: bug, Frontend, Ready to review

#515 Front(feat) pre gap-analysis highlight layer
  app/components/gap-analysis/item/component.stories.tsx
  app/components/gap-analysis/item/component.tsx
  app/hooks/map/constants.tsx
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/layout/projects/show/map/component.tsx
  app/layout/scenarios/edit/analysis/gap-analysis/list/component.tsx
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/show/analysis/gap-analysis/list/component.tsx
  app/layout/scenarios/show/map/component.tsx
  app/store/slices/scenarios/detail.ts
  app/store/slices/scenarios/edit.ts
Labels: Frontend, Ready to review, New feature
