Repository Vizzuality/marxan-cloud, pull requests merged in 2021-02, with the labels that each got.

#37 Feature/data files tests
  data/notebooks/Dockerfile
  data/notebooks/Lab/Create_grids.ipynb
  data/notebooks/Lab/marxan_BC_example.ipynb
  data/notebooks/Lab/run_marxan.ipynb
  data/notebooks/requirements.txt
Labels: Data, Ready to review

#44 Feature/header
  app/.storybook/main.js
  app/components/avatar/component.tsx
  app/components/dropdowns/multi/component.tsx
  app/components/header/component.tsx
  app/layout/header/__test__.js
  app/layout/header/component.stories.tsx
  app/layout/header/component.tsx
  app/layout/header/index.ts
  app/layout/wrapper/component.stories.tsx
  app/layout/wrapper/component.tsx
  app/layout/wrapper/index.ts
  app/package.json
  app/pages/about.tsx
  app/pages/index.tsx
  app/svgs/logo.svg
  app/yarn.lock
Labels: Frontend, Ready to review, documentation

#46 Table component
  app/components/table/component.stories.tsx
  app/components/table/component.tsx
  app/components/table/index.ts
  app/components/table/types.ts
  app/svgs/ui/star.svg
Labels: Frontend, WIP

#52 add initial infrastructure architecture outline
  docs/ARCHITECTURE_infrastructure.md
  docs/ARCHITECTURE_infrastructure/marxan-contexts.png
  docs/ARCHITECTURE_infrastructure/marxan-data-pipeline-context.png
  marxan-api-architecture.puml
Labels: documentation

#56 Add interfaces for auth context props and user object
  app/hooks/authentication/index.tsx
  app/hooks/authentication/types.ts
Labels: Frontend, enhancement

#59 Structure: Project && scenario pages
  app/pages/projects/[pid]/edit.tsx
  app/pages/projects/[pid]/index.tsx
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
  app/pages/projects/[pid]/scenarios/[sid]/index.tsx
  app/pages/projects/[pid]/scenarios/new.tsx
  app/pages/projects/index.tsx
  app/pages/projects/new.tsx
Labels: Frontend, infrastructure

#47 Pipes for geodata
  Makefile
  README.md
  data/Makefile
  data/README.md
  data/data_download/.dockerignore
  data/data_download/Dockerfile
  data/data_download/Makefile
  data/data_download/gadm_3.6/Makefile
  data/data_download/iucn/Makefile
  data/data_download/wdpa/Makefile
  data/data_download/world_terrestrial_ecosystems/Makefile
  data/docker-compose-data_download.yml
  geoprocessing/package.json
  geoprocessing/src/migrations/geoprocessing/1611221157285-initialGeoDBSetup.ts
  geoprocessing/src/migrations/geoprocessing/1611828857842-addFeatureScenarioOutputEntity.ts
Labels: API, Data, Ready to review

#50 Feature Target-SPF generic component
  app/components/features/target-spf-item/component.stories.tsx
  app/components/features/target-spf-item/component.tsx
  app/components/features/target-spf-item/index.js
  app/components/features/target-spf-item/types.ts
  app/components/forms/input/component.tsx
Labels: Frontend, WIP

#65 Architectural improvements
  app/components/button/component.tsx
  app/components/forms/input/component.tsx
  app/components/map/component.tsx
  app/components/map/controls/fit-bounds/component.tsx
  app/hooks/projects/index.ts
  app/hooks/scenarios/index.ts
  app/layout/header/component.tsx
  app/layout/pill/component.tsx
  app/layout/pill/index.ts
  app/layout/projects/list/component.tsx
  app/layout/projects/toolbar/component.tsx
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/map/index.ts
  app/layout/scenarios/sidebar/component.tsx
  app/layout/scenarios/sidebar/index.ts
  app/layout/scenarios/sidebar/name/component.tsx
  app/layout/scenarios/sidebar/name/index.ts
  app/layout/wrapper/component.tsx
  app/pages/_document.tsx
  app/pages/projects/[pid]/scenarios/new.tsx
  app/services/scenarios/index.ts
Labels: Frontend, New feature

#55 Feature/data/blm
  data/notebooks/Dockerfile
  data/notebooks/Lab/BLM.ipynb
  data/notebooks/Lab/Dataset_processing_log.md
  data/notebooks/Lab/marxan_BC_example.ipynb
  data/notebooks/Lab/marxan_utils.ipynb
  data/notebooks/Lab/run_marxan.ipynb
  data/notebooks/jupyter_server_config.py
  data/notebooks/requirements.txt
Labels: Data

#69 Scenarios: header title and navigate between pages
  app/layout/header/component.tsx
  app/layout/header/title/component.tsx
  app/layout/header/title/index.ts
  app/layout/scenarios/sidebar/name/component.tsx
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
  app/pages/projects/[pid]/scenarios/[sid]/index.tsx
Labels: Frontend, New feature, Ready to review

#70 Tooltip: arrow
  app/components/tooltip/arrow/component.tsx
  app/components/tooltip/arrow/index.ts
  app/components/tooltip/component.stories.tsx
  app/components/tooltip/component.tsx
Labels: Frontend, New feature, Ready to review

#66 fixed error issue with wdpa pipe
  data/data_download/Dockerfile
  data/data_download/wdpa/Makefile
Labels: Data, Ready to review

#72 Header: title edition
  app/components/tooltip/component.tsx
  app/hooks/projects/index.ts
  app/hooks/projects/types.ts
  app/hooks/scenarios/index.ts
  app/hooks/scenarios/types.ts
  app/layout/header/title/component.tsx
  app/layout/scenarios/sidebar/name/component.tsx
Labels: Frontend, New feature, Ready to review
