Repository Vizzuality/marxan-cloud, pull requests merged in 2021-06, with the labels that each got.

#233 New layer manager
  app/components/map/component.stories.tsx
  app/components/map/component.tsx
  app/components/map/layers.ts
  app/layout/projects/new/map/component.tsx
  app/package.json
  app/yarn.lock
Labels: Frontend, New feature, Ready to review

#242 Header: my projects link
  app/layout/header/component.tsx
  app/layout/header/my-projects/component.tsx
  app/layout/header/my-projects/index.ts
Labels: Frontend, New feature, Ready to review

#243 404 page
  app/pages/404.tsx
Labels: Frontend, New feature, Ready to review

#222 Project new
  app/components/button/component.tsx
  app/components/forms/input/component.tsx
  app/components/forms/select/constants/theme.js
  app/components/forms/textarea/component.tsx
  app/components/map/component.stories.tsx
  app/components/map/component.tsx
  app/components/map/layers.ts
  app/hooks/administrative-areas/index.ts
  app/hooks/countries/index.ts
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/hooks/projects/index.ts
  app/layout/projects/new/form/component.tsx
  app/layout/projects/new/form/planning-area-selector/component.tsx
  app/layout/projects/new/form/planning-area-selector/country-region-selector/component.tsx
  app/layout/projects/new/form/planning-area-selector/country-region-selector/index.ts
  app/layout/projects/new/form/planning-area-selector/country-region-selector/types.ts
  app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/component.tsx
  app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/index.ts
  app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/types.ts
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/component.tsx
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/index.ts
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/planning-unit-button/component.tsx
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/planning-unit-button/index.ts
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/planning-unit-button/types.ts
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/types.ts
  app/layout/projects/new/form/planning-area-selector/types.ts
  app/layout/projects/new/map/component.tsx
  app/layout/projects/new/map/types.ts
  app/layout/projects/show/map/component.tsx
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/sidebar/wdpa/categories/component.tsx
  app/package.json
  app/pages/projects/new.tsx
  app/store/index.ts
  app/store/slices/projects/detail.ts
  app/store/slices/projects/new.ts
  app/store/slices/scenarios/edit.ts
  app/types/country-model.ts
  app/yarn.lock
Labels: Frontend, New feature, WIP

#256 Feature/api/marxan 333 vl migrate from proxy controller
  api/apps/api/src/add-swagger.ts
  api/apps/api/src/app.module.ts
  api/apps/api/src/bootstrap-app.ts
  api/apps/api/src/decorators/shapefile.decorator.ts
  api/apps/api/src/generate-swagger.ts
  api/apps/api/src/main.ts
  api/apps/api/src/migrations/api/1619777176256-PropertyListForFeatures.ts
  api/apps/api/src/modules/admin-areas/admin-areas.controller.ts
  api/apps/api/src/modules/admin-areas/admin-areas.module.ts
  api/apps/api/src/modules/geo-features/geo-features.controller.ts
  api/apps/api/src/modules/geo-features/geo-features.module.ts
  api/apps/api/src/modules/planning-units/planning-units.controller.ts
  api/apps/api/src/modules/planning-units/planning-units.module.ts
  api/apps/api/src/modules/protected-areas/protected-areas.controller.ts
  api/apps/api/src/modules/protected-areas/protected-areas.module.ts
  api/apps/api/src/modules/proxy/proxy.controller.ts
  api/apps/api/src/modules/proxy/proxy.module.ts
  api/apps/api/src/modules/users/users.controller.ts
  api/apps/api/src/swagger.json
  api/apps/api/test/proxy.vector-tiles.e2e-spec.ts
  api/apps/geoprocessing/src/decoratos/shapefile.decorator.ts
  api/apps/geoprocessing/src/dto/info.dto.ts
  api/apps/geoprocessing/src/modules/admin-areas/admin-areas.service.ts
  api/apps/geoprocessing/src/modules/features/features.controller.ts
  api/apps/geoprocessing/src/modules/features/features.service.ts
  api/apps/geoprocessing/src/modules/planning-units/planning-units.controller.ts
  api/apps/geoprocessing/src/modules/planning-units/planning-units.service.ts
  api/apps/geoprocessing/src/modules/protected-areas/protected-areas.controller.ts
  api/apps/geoprocessing/src/modules/protected-areas/protected-areas.service.ts
  api/apps/geoprocessing/src/modules/tile/tile.service.ts
  api/apps/geoprocessing/src/utils/bbox.utils.ts
  api/apps/geoprocessing/test/index.html
  api/package.json
  api/yarn.lock
  data/notebooks/Lab/featuresForScenario_logic.ipynb
  data/notebooks/Lab/pu_creation_logic.ipynb
Labels: API, Ready to review

#260 addressed issues with test error in api
  api/apps/api/test/proxy.vector-tiles.e2e-spec.ts
Labels: API, QA, Ready to review, bug

#263 Scenarios infinite query
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/hooks/scenarios/index.ts
  app/hooks/scenarios/types.ts
  app/layout/projects/new/form/component.tsx
  app/layout/projects/new/map/component.tsx
  app/layout/projects/show/scenarios/component.tsx
  app/layout/projects/show/scenarios/toolbar/component.tsx
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/sidebar/wdpa/categories/component.tsx
Labels: Frontend, New feature, Ready to review

#270 fix a few links in the architecture chart
  docs/marxan-api-architecture.puml
Labels: documentation

#276 Features filters
  app/hooks/features/index.ts
  app/layout/scenarios/sidebar/features/add/component.tsx
  app/layout/scenarios/sidebar/features/add/filters/component.tsx
  app/layout/scenarios/sidebar/features/add/filters/index.ts
  app/layout/scenarios/sidebar/features/add/list/component.tsx
  app/layout/scenarios/sidebar/features/add/toolbar/component.tsx
  app/layout/scenarios/sidebar/features/component.tsx
  app/svgs/ui/filter.svg
Labels: Frontend, New feature, Ready to review

#281 Fix/api/marxan 479 fixed size calc
  api/apps/api/test/countries.e2e-spec.ts
  api/apps/geoprocessing/src/migrations/geoprocessing/1624025983610-M2ToKm2PUAreaSize.ts
  api/apps/geoprocessing/test/index.html
Labels: API, Ready to review, bug

#283 With BBox present there is no need to simplify.
  api/apps/geoprocessing/src/modules/planning-units/planning-units.service.ts
  api/apps/geoprocessing/test/index.html
Labels: API, Ready to review

#284 Max min area size
  app/hooks/administrative-areas/index.ts
  app/hooks/countries/index.ts
  app/layout/projects/new/form/component.tsx
  app/layout/projects/new/form/planning-area-selector/component.tsx
  app/layout/projects/new/form/planning-area-selector/country-region-selector/component.tsx
  app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/component.tsx
  app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/types.ts
  app/layout/projects/new/form/planning-area-selector/types.ts
  app/store/slices/projects/new.ts
  app/types/country-model.ts
Labels: Frontend, Ready to review

#271 Solutions section main architecture
  app/components/info-button/component.tsx
  app/hooks/solutions/index.ts
  app/hooks/solutions/mock.ts
  app/hooks/solutions/types.ts
  app/layout/scenarios/sidebar/solutions/component.tsx
  app/layout/scenarios/sidebar/solutions/details/component.tsx
  app/layout/scenarios/sidebar/solutions/details/index.ts
  app/layout/scenarios/sidebar/solutions/details/types.ts
  app/layout/scenarios/sidebar/solutions/gap-analysis/component.tsx
  app/layout/scenarios/sidebar/solutions/gap-analysis/index.ts
  app/layout/scenarios/sidebar/solutions/gap-analysis/types.ts
  app/layout/scenarios/sidebar/solutions/index.ts
  app/layout/scenarios/sidebar/solutions/list/component.tsx
  app/layout/scenarios/sidebar/solutions/list/index.ts
  app/layout/scenarios/sidebar/solutions/list/types.ts
  app/layout/scenarios/sidebar/solutions/sections/component.tsx
  app/layout/scenarios/sidebar/solutions/sections/constants.ts
  app/layout/scenarios/sidebar/solutions/sections/index.ts
  app/layout/scenarios/sidebar/solutions/sections/item/component.tsx
  app/layout/scenarios/sidebar/solutions/sections/item/index.ts
  app/layout/scenarios/sidebar/solutions/sections/types.ts
  app/layout/scenarios/sidebar/solutions/types.ts
  app/layout/scenarios/sidebar/tabs/component.tsx
  app/layout/scenarios/sidebar/tabs/constants.ts
  app/layout/scenarios/sidebar/tabs/types.ts
  app/layout/scenarios/sidebar/types.ts
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
  app/svgs/ui/clock.svg
  app/svgs/ui/table.svg
  app/types/project-model.ts
Labels: Frontend, New feature

#289 Help
  app/hooks/help/index.tsx
  app/hooks/help/types.ts
  app/layout/help/beacon/component.tsx
  app/layout/help/beacon/index.ts
  app/layout/help/button/component.tsx
  app/layout/help/button/index.ts
  app/layout/help/spotlight/component.tsx
  app/layout/help/spotlight/index.ts
  app/layout/help/tooltip/component.tsx
  app/layout/help/tooltip/index.ts
  app/layout/projects/all/list/component.tsx
  app/layout/projects/all/toolbar/component.tsx
  app/layout/projects/new/form/component.tsx
  app/layout/projects/new/map/component.tsx
  app/layout/projects/show/header/toolbar/component.tsx
  app/layout/projects/show/scenarios/component.tsx
  app/layout/projects/show/scenarios/toolbar/component.tsx
  app/package.json
  app/pages/_app.tsx
  app/pages/projects/[pid]/index.tsx
  app/pages/projects/index.tsx
  app/pages/projects/new.tsx
  app/svgs/ui/help-2.svg
  app/svgs/ui/help.svg
  app/tailwind.config.js
  app/yarn.lock
Labels: Frontend, New feature, Ready to review

#290 Feature/api/marxan 480 scenario pu vl
  api/apps/api/src/modules/scenarios/scenarios.controller.ts
  api/apps/api/test/countries.e2e-spec.ts
  api/apps/api/test/proxy.vector-tiles.e2e-spec.ts
  api/apps/api/test/utils/features.test.utils.ts
  api/apps/geoprocessing/src/app.module.ts
  api/apps/geoprocessing/src/main.ts
  api/apps/geoprocessing/src/migrations/geoprocessing/1624281665759-Ratio64PUAreaSize.ts
  api/apps/geoprocessing/src/modules/planning-units/planning-units.controller.ts
  api/apps/geoprocessing/src/modules/planning-units/planning-units.module.ts
  api/apps/geoprocessing/src/modules/planning-units/planning-units.service.ts
  api/apps/geoprocessing/src/modules/scenarios/scenarios.controller.ts
  api/apps/geoprocessing/src/modules/scenarios/scenarios.module.ts
  api/apps/geoprocessing/src/modules/scenarios/scenarios.service.ts
  api/apps/geoprocessing/test/index.html
  api/libs/scenarios-planning-unit/src/index.ts
  api/libs/scenarios-planning-unit/src/scenarios-pu-cost-data.geo.entity.ts
  api/libs/scenarios-planning-unit/src/scenarios-pu-pa-data.geo.entity.ts
  data/notebooks/Lab/pu_creation_logic.ipynb
Labels: API, Ready to review

#296 Forgot password
  app/layout/forgot-password/component.tsx
  app/layout/forgot-password/index.ts
  app/layout/sign-in/component.tsx
  app/pages/auth/forgot-password.tsx
  app/svgs/users/check-email.svg
Labels: Frontend, New feature, Ready to review

#301 Cost surface
  app/hooks/scenarios/index.ts
  app/hooks/scenarios/types.ts
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/uploading/component.tsx
  app/layout/scenarios/sidebar/analysis/cost-surface/component.tsx
  app/services/downloads/index.ts
Labels: Frontend, New feature, Ready to review
