Repository Vizzuality/marxan-cloud, pull requests merged in 2021-05, with the labels that each got.

#143 marxan 89 add test post patch data shapes
  api/test/json-api.e2e-spec.ts
Labels: API, WIP

#139 chore(api): scenario-features pre-gap-analysis
  api/src/modules/admin-areas/admin-areas.module.ts
  api/src/modules/admin-areas/admin-areas.service.ts
  api/src/modules/countries/countries.module.ts
  api/src/modules/countries/countries.service.ts
  api/src/modules/geo-features/geo-feature.api.entity.ts
  api/src/modules/geo-features/geo-features.module.ts
  api/src/modules/geo-features/geo-features.service.ts
  api/src/modules/geo/geo.module.ts
  api/src/modules/protected-areas/protected-areas.module.ts
  api/src/modules/protected-areas/protected-areas.service.ts
  api/src/modules/scenarios-features/__mocks__/scenario-features.view-data.ts
  api/src/modules/scenarios-features/entities/remote-connection-name.ts
  api/src/modules/scenarios-features/entities/remote-features-data.geo.entity.ts
  api/src/modules/scenarios-features/entities/remote-scenario-features-data.geo.entity.ts
  api/src/modules/scenarios-features/index.ts
  api/src/modules/scenarios-features/scenario-features.dto.ts
  api/src/modules/scenarios-features/scenario-features.module.ts
  api/src/modules/scenarios-features/scenario-features.service.spec.ts
  api/src/modules/scenarios-features/scenario-features.service.ts
  api/src/modules/scenarios-features/search-criteria.ts
  api/src/modules/scenarios/dto/scenario-feature-result.dto.ts
  api/src/modules/scenarios/scenarios.controller.ts
  api/src/modules/scenarios/scenarios.module.ts
  api/src/ormconfig.connections.ts
  api/src/ormconfig.ts
  api/src/utils/__mocks__/fake-query-builder.ts
  api/test/scenario-features/get-scenario-features.e2e-spec.ts
  api/test/scenario-features/steps/when-scenario-has-pre-gap-data.ts
  api/test/steps/given-scenario.ts
  api/test/steps/given-user-is-logged-in.ts
  api/test/steps/when-user-gets-scenario-gap-analysis.ts
  api/test/utils/api-application.ts
Labels: API, Ready to review

#148 chore(api): scenarios-planning-units base service
  api/src/app.module.ts
  api/src/modules/scenarios-features/scenario-features.service.ts
  api/src/modules/scenarios-planning-unit/entities/remote-connection-name.ts
  api/src/modules/scenarios-planning-unit/entities/scenarios-planning-unit.geo.entity.ts
  api/src/modules/scenarios-planning-unit/lock-status.enum.ts
  api/src/modules/scenarios-planning-unit/scenarios-planning-unit.module.ts
  api/src/modules/scenarios-planning-unit/scenarios-planning-unit.service.ts
  api/test/scenarios-pu-data/scenarios-pu-data-service.integration.e2e-spec.ts
  api/test/scenarios-pu-data/steps/given-scenario-pu-data-exists.ts
  api/test/scenarios-pu-data/steps/world.ts
Labels: Ready to review

#144 add features and protected areas to proxy
  api/src/modules/proxy/proxy.controller.ts
  geoprocessing/src/modules/features/features.controller.ts
  geoprocessing/src/modules/protected-areas/protected-areas.controller.ts
Labels: API, Data

#149 chore(api): analysis module for incl/excl feature
  api/src/app.module.ts
  api/src/modules/analysis/analysis.module.ts
  api/src/modules/analysis/async-job.ts
  api/src/modules/analysis/entry-points/adjust-cost-surface-input.ts
  api/src/modules/analysis/entry-points/adjust-cost-surface.ts
  api/src/modules/analysis/entry-points/adjust-planning-units-input.ts
  api/src/modules/analysis/entry-points/adjust-planning-units.ts
  api/src/modules/analysis/entry-points/get-scenario-status.ts
  api/src/modules/analysis/entry-points/scenario-processing-status.ts
  api/src/modules/analysis/providers/cost-surface/update-cost-surface.service.ts
  api/src/modules/analysis/providers/planning-units/__mocks__/are-puuids-allowed.mock.ts
  api/src/modules/analysis/providers/planning-units/__mocks__/geojson.ts
  api/src/modules/analysis/providers/planning-units/__mocks__/request-job-port.mock.ts
  api/src/modules/analysis/providers/planning-units/adapters/are-puids-allowed-adapter.ts
  api/src/modules/analysis/providers/planning-units/adapters/async-jobs-adapter.ts
  api/src/modules/analysis/providers/planning-units/are-puids-allowed.port.ts
  api/src/modules/analysis/providers/planning-units/request-job.port.ts
  api/src/modules/analysis/providers/planning-units/update-planning-units.service.spec.ts
  api/src/modules/analysis/providers/planning-units/update-planning-units.service.ts
  api/src/modules/analysis/providers/status/scenario-status.service.spec.ts
  api/src/modules/analysis/providers/status/scenario-status.service.ts
  api/src/modules/authentication/issued-authn-token.api.entity.ts
  api/src/modules/organizations/organization.api.entity.ts
  api/src/modules/projects/project.api.entity.ts
  api/src/modules/scenarios-planning-unit/scenarios-planning-unit.module.ts
  api/src/modules/scenarios/scenario.api.entity.ts
  api/src/modules/users/user.api.entity.ts
  api/src/types/time-user-entity-metadata.ts
Labels: API, enhancement, hex-onion-architecture-example

#162 feat(api): scenarios: wdpa calculation trigger
  api/src/modules/scenarios/__mocks__/input-change.data.ts
  api/src/modules/scenarios/__mocks__/scenario.data.ts
  api/src/modules/scenarios/scenarios.module.ts
  api/src/modules/scenarios/scenarios.service.ts
  api/src/modules/scenarios/wdpa-area-calculation.service.spec.ts
  api/src/modules/scenarios/wdpa-area-calculation.service.ts
Labels: protection-levels

#169 Analysis: scaffolding
  app/components/gap-analysis/item/component.stories.tsx
  app/components/gap-analysis/item/component.tsx
  app/components/gap-analysis/list/component.stories.tsx
  app/components/gap-analysis/list/component.tsx
  app/components/gap-analysis/list/index.ts
  app/components/map/component.tsx
  app/hooks/gap-analysis/index.ts
  app/hooks/gap-analysis/mock.ts
  app/hooks/gap-analysis/types.ts
  app/layout/pill/component.tsx
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/map/drawing-manager/component.tsx
  app/layout/scenarios/map/drawing-manager/drawing-styles.ts
  app/layout/scenarios/map/drawing-manager/index.ts
  app/layout/scenarios/map/drawing-styles.ts
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/clicking/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/clicking/index.ts
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/drawing/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/drawing/index.ts
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/index.ts
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/uploading/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/uploading/index.ts
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/index.ts
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/tabs/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/tabs/index.ts
  app/layout/scenarios/sidebar/analysis/component.tsx
  app/layout/scenarios/sidebar/analysis/cost-surface/component.tsx
  app/layout/scenarios/sidebar/analysis/cost-surface/index.ts
  app/layout/scenarios/sidebar/analysis/gap-analysis/component.tsx
  app/layout/scenarios/sidebar/analysis/gap-analysis/index.ts
  app/layout/scenarios/sidebar/analysis/gap-analysis/list/component.tsx
  app/layout/scenarios/sidebar/analysis/gap-analysis/list/index.ts
  app/layout/scenarios/sidebar/analysis/gap-analysis/toolbar/component.tsx
  app/layout/scenarios/sidebar/analysis/gap-analysis/toolbar/index.ts
  app/layout/scenarios/sidebar/analysis/index.ts
  app/layout/scenarios/sidebar/analysis/sections/component.tsx
  app/layout/scenarios/sidebar/analysis/sections/index.ts
  app/layout/scenarios/sidebar/analysis/sections/item/component.tsx
  app/layout/scenarios/sidebar/analysis/sections/item/index.ts
  app/layout/scenarios/sidebar/features/component.tsx
  app/layout/scenarios/sidebar/tabs/component.tsx
  app/layout/scenarios/sidebar/wdpa/component.tsx
  app/package.json
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
  app/store/slices/scenarios/edit.ts
  app/svgs/ui/draw.svg
  app/svgs/ui/planning-units.svg
  app/svgs/ui/renta2020.pdf
  app/yarn.lock
Labels: Frontend, New feature, Ready to review

#181 Legend && Lock upload geojson
  app/components/map/legend/component.stories.tsx
  app/components/map/legend/component.tsx
  app/components/map/legend/index.ts
  app/components/map/legend/item/component.tsx
  app/components/map/legend/item/index.ts
  app/components/map/legend/mock.tsx
  app/components/map/legend/sortable/list/component.tsx
  app/components/map/legend/sortable/list/index.ts
  app/components/map/legend/sortable/list/item/component.tsx
  app/components/map/legend/sortable/list/item/index.ts
  app/hooks/scenarios/index.ts
  app/layout/scenarios/map/component.tsx
  app/layout/scenarios/map/drawing-manager/component.tsx
  app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/uploading/component.tsx
  app/layout/scenarios/sidebar/analysis/gap-analysis/list/component.tsx
  app/layout/scenarios/sidebar/features/add/list/component.tsx
  app/package.json
  app/services/uploads/index.ts
  app/svgs/map/hexagon.svg
  app/svgs/map/legend.svg
  app/yarn.lock
Labels: Frontend, New feature, Ready to review

#185 Legend types and maxHeight
  app/components/map/legend/component.stories.tsx
  app/components/map/legend/component.tsx
  app/components/map/legend/item/component.tsx
  app/components/map/legend/mock.tsx
  app/components/map/legend/types/basic/component.tsx
  app/components/map/legend/types/basic/index.ts
  app/components/map/legend/types/choropleth/component.tsx
  app/components/map/legend/types/choropleth/index.ts
  app/components/map/legend/types/gradient/component.tsx
  app/components/map/legend/types/gradient/index.ts
Labels: Frontend, New feature, Ready to review

#192 Refactior File Service
  api/src/modules/planning-units/planning-units.module.ts
  geoprocessing/src/modules/files/files.module.ts
  geoprocessing/src/modules/files/files.service.ts
  geoprocessing/src/modules/planning-units/planning-units.controller.ts
  geoprocessing/src/modules/planning-units/planning-units.module.ts
  geoprocessing/src/modules/shapefiles/shapefile-surface-cost/shapefile-surface-cost.service.ts
  geoprocessing/src/modules/shapefiles/shapefiles.module.ts
  geoprocessing/src/modules/shapefiles/shapefiles.service.ts
Labels: API, Ready to review

#205 Docs
  app/.storybook/main.js
  app/.storybook/preview.js
  app/docs/authentication.stories.mdx
  app/docs/deploy.stories.mdx
  app/docs/fetching.stories.mdx
  app/docs/install.stories.mdx
  app/docs/intro.stories.mdx
  app/docs/media.stories.mdx
  app/docs/tests.stories.mdx
  app/package.json
  app/public/styles/tailwind.storybook.css
  app/yarn.lock
Labels: Frontend, Ready to review, documentation

#195 Run modal
  app/components/button/component.stories.tsx
  app/components/button/component.tsx
  app/components/forms/input/component.tsx
  app/components/scenarios/blm-chart/component.tsx
  app/components/tooltip/component.tsx
  app/layout/scenarios/sidebar/analysis/component.tsx
  app/layout/scenarios/sidebar/run/chart/component.tsx
  app/layout/scenarios/sidebar/run/chart/constants.ts
  app/layout/scenarios/sidebar/run/chart/index.ts
  app/layout/scenarios/sidebar/run/component.tsx
  app/layout/scenarios/sidebar/run/constants.tsx
  app/layout/scenarios/sidebar/run/field/component.tsx
  app/layout/scenarios/sidebar/run/field/index.ts
  app/layout/scenarios/sidebar/run/index.ts
  app/svgs/ui/run.svg
  data/notebooks/Lab/marxan_utils.ipynb
  docs/README_science_and_data.md
Labels: Frontend, New feature, WIP
