Repository Vizzuality/marxan-cloud, pull requests merged in 2022-01, with the labels that each got.

#729 Fix issues with tests not running deterministically
  api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/scenario-data/input-files-fs.ts
  api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
  api/apps/geoprocessing/test/integration/marxan-run/run-worker.e2e-spec.ts
  api/apps/geoprocessing/test/worker-module/worker-module-di-usage.e2e-spec.ts
Labels: WIP

#732 Fix issues with BlmValuesCalculator
  api/apps/api/src/modules/projects/blm/change-blm-range.handler.ts
  api/apps/api/src/modules/projects/blm/domain/blm-values-calculator.spec.ts
  api/apps/api/src/modules/projects/blm/domain/blm-values-calculator.ts
  api/apps/api/src/modules/projects/blm/set-project-blm-handler.ts
Labels: bug, WIP

#734 Fixing missing key prop in the logos/partners section of the homepage
  app/layout/home/partners/component.tsx
Labels: bug, Frontend, Ready to review

#728 Limiting uploads file size (frontend) + friendlier file size error me…
  app/constants/file-uploader-size-limits.js
  app/layout/projects/new/form/planning-area-grid-uploader/component.tsx
  app/layout/projects/new/form/planning-area-uploader/component.tsx
  app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/uploading/component.tsx
  app/layout/scenarios/edit/analysis/cost-surface/component.tsx
  app/layout/scenarios/edit/features/add/uploader/component.tsx
  app/layout/scenarios/edit/wdpa/categories/pa-uploader/component.tsx
  app/utils/units.ts
Labels: enhancement, Frontend, Ready to review

#740 Adding scenario status filters on the frontend
  app/components/scenarios/item/component.tsx
  app/hooks/scenarios/index.ts
  app/layout/projects/show/scenarios/component.tsx
  app/layout/projects/show/scenarios/filters/component.tsx
  app/layout/projects/show/scenarios/toolbar/component.tsx
Labels: Frontend, Ready to review, New feature

#735 Homepage text changes [MARXAN-1169]
  app/layout/home/features/component.tsx
  app/layout/home/features/constants.ts
  app/layout/home/intro/component.tsx
  app/layout/home/partners/constants.ts
Labels: Frontend, Ready to review

#747 fix(front): adjust PU by uploading[MARXAN-1182]
  app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/uploading/component.tsx
Labels: bug, Frontend, Ready to review

#752 fix(front): update features list after uploading new one[MARXAN-1189]
  app/layout/scenarios/edit/features/add/list/component.tsx
  app/layout/scenarios/edit/features/add/uploader/component.tsx
Labels: bug, Frontend, Ready to review

#753 [MARXAN-1190] Fixing bad dispatch calls in the WDPACategories and ScenariosFeaturesList forms
  app/layout/scenarios/edit/features/list/component.tsx
  app/layout/scenarios/edit/wdpa/categories/component.tsx
Labels: bug, Frontend, Ready to review

#755 [MARXAN-1191] Fixing sliders' issues (cut off labels, floating point errors)
  app/components/forms/slider/value/component.tsx
  app/layout/scenarios/edit/wdpa/threshold/component.tsx
Labels: bug, Frontend, Ready to review

#748 MARXAN-1179 All Users can view other users in private projects
  api/apps/api/src/modules/access-control/projects-acl/project-acl.service.ts
  api/apps/api/test/access-control/project-acl/project-acl-get.e2e-spec.ts
  api/apps/api/test/access-control/project-acl/project-acl.fixtures.ts
Labels: API

#756 Fixing bad padding when project has no scenarios yet
  app/layout/projects/show/scenarios/component.tsx
Labels: bug, Frontend, Ready to review

#757 Home banner: improve animations
  app/layout/home/banner/component.tsx
  app/tailwind.config.js
Labels: Frontend, Ready to review

#761 Changing text displayed while features are being processed
  app/layout/scenarios/edit/status/component.tsx
Labels: Frontend, Ready to review

#760 Choose scenario type modal text updates
  app/layout/projects/show/scenarios/types/component.tsx
  app/layout/projects/show/scenarios/types/constants.ts
Labels: Frontend, Ready to review

#759 [MARXAN-1195] Fixing adjusting planning units triggering a dispatch/render loop
  app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/clicking/component.tsx
  app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/drawing/component.tsx
  app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/uploading/component.tsx
  app/layout/scenarios/edit/analysis/adjust-planning-units/component.tsx
Labels: bug, Frontend, Ready to review

#758 Adjust planning unit: support multipolygon
  app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/uploading/component.tsx
Labels: Frontend, Ready to review

#765 Scenarios: add lastJobCheck to metadata if it does not exist
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
Labels: Frontend, Ready to review

#767 Feature/frontend/marxan 1048
  app/components/features/target-spf-item/component.tsx
  app/components/forms/input/component.tsx
Labels: enhancement, Frontend, Ready to review

#636 feat(front): blm calibration[MARXAN-971]
  app/components/scenarios/blm-chart/component.stories.tsx
  app/components/scenarios/blm-chart/component.tsx
  app/components/scenarios/item/component.tsx
  app/hooks/scenarios/index.ts
  app/hooks/scenarios/types.ts
  app/layout/community/published-projects/duplicate-button/component.tsx
  app/layout/scenarios/edit/analysis/blm-calibration/blm-chart/component.tsx
  app/layout/scenarios/edit/analysis/blm-calibration/blm-chart/constants.ts
  app/layout/scenarios/edit/analysis/blm-calibration/blm-chart/index.ts
  app/layout/scenarios/edit/analysis/blm-calibration/blm-settings-graph/component.tsx
  app/layout/scenarios/edit/analysis/blm-calibration/blm-settings-graph/index.ts
  app/layout/scenarios/edit/analysis/blm-calibration/component.tsx
  app/layout/scenarios/edit/analysis/blm-calibration/index.ts
  app/layout/scenarios/edit/analysis/component.tsx
  app/layout/scenarios/edit/run/chart/component.tsx
  app/layout/scenarios/edit/run/chart/constants.ts
  app/layout/scenarios/edit/run/chart/index.ts
  app/layout/scenarios/edit/run/component.tsx
  app/layout/scenarios/edit/run/constants.tsx
  app/layout/scenarios/edit/status/actions/done.tsx
  app/layout/scenarios/edit/status/actions/failure.tsx
  app/layout/scenarios/edit/status/constants.ts
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
  app/store/slices/scenarios/edit.ts
Labels: Frontend, WIP, New feature

#690 feat(front): project users roles[MARXAN-1117][MARXAN-1118][MARXAN-1119][MARXAN-1143]
  app/components/avatar/component.tsx
  app/components/forms/label/component.tsx
  app/components/forms/select/constants/theme.ts
  app/components/forms/select/multi/component.tsx
  app/components/forms/select/single/component.tsx
  app/components/modal/component.tsx
  app/components/projects/item/component.tsx
  app/components/projects/published-item/component.tsx
  app/components/scenarios/item/settings/component.tsx
  app/components/tooltip/component.tsx
  app/components/tooltip/types.ts
  app/hooks/project-users/index.ts
  app/hooks/project-users/types.ts
  app/layout/community/published-projects/component.tsx
  app/layout/community/published-projects/detail/component.tsx
  app/layout/header/title/component.tsx
  app/layout/me/delete-account/component.tsx
  app/layout/projects/all/list/component.tsx
  app/layout/projects/new/form/country-region-selector/component.tsx
  app/layout/projects/show/header/component.tsx
  app/layout/projects/show/header/contributors/component.tsx
  app/layout/projects/show/header/contributors/edit-dropdown/card/component.tsx
  app/layout/projects/show/header/contributors/edit-dropdown/card/constants.ts
  app/layout/projects/show/header/contributors/edit-dropdown/card/index.ts
  app/layout/projects/show/header/contributors/edit-dropdown/component.tsx
  app/layout/projects/show/header/contributors/edit-dropdown/index.ts
  app/layout/projects/show/header/toolbar/component.tsx
  app/layout/projects/show/scenarios/component.tsx
  app/layout/scenarios/edit/analysis/component.tsx
  app/layout/scenarios/edit/run/component.tsx
  app/services/roles/index.ts
Labels: Frontend, Ready to review, New feature

#754 [WIP][MARXAN-1122]adds-ACL-scenarios-controller
  api/apps/api/src/app.controller.ts
  api/apps/api/src/modules/access-control/access-control.types.ts
  api/apps/api/src/modules/projects/projects-listing.controller.ts
  api/apps/api/src/modules/scenarios-features/scenario-features-gap-data.service.ts
  api/apps/api/src/modules/scenarios-features/scenario-features-output-gap-data.service.ts
  api/apps/api/src/modules/scenarios-features/scenario-features.module.ts
  api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
  api/apps/api/src/modules/scenarios/scenarios.controller.ts
  api/apps/api/src/modules/scenarios/scenarios.service.ts
  api/apps/api/src/utils/acl.utils.ts
  api/apps/api/test/fixtures/test-data.sql
  api/apps/api/test/project-scenarios.e2e-spec.ts
  api/apps/api/test/projects.e2e-spec.ts
  api/apps/api/test/scenario-input-files/scenario-cost-surface/scenario-cost-surface.e2e-spec.ts
  api/apps/api/test/scenario-input-files/scenario-cost-surface/scenario-cost-surface.fixtures.ts
  api/apps/api/test/scenario-input-files/scenario-input-files.e2e-spec.ts
  api/apps/api/test/scenario-input-files/scenario-input-files.fixtures.ts
  api/apps/api/test/scenario-input-files/world.ts
  api/apps/api/test/scenario-protected-areas/fixtures.ts
  api/apps/api/test/scenario-protected-areas/scenario-protected-areas.e2e-spec.ts
  api/apps/api/test/scenario-run-results/scenario-output-files.e2e-spec.ts
  api/apps/api/test/scenario-run-results/scenario-output-files.fixtures.ts
  api/apps/api/test/scenario-solutions/get-all-solutions.e2e-spec.ts
  api/apps/api/test/scenario-solutions/get-all-solutions.fixtures.ts
  api/apps/api/test/scenario-solutions/world.ts
  api/apps/api/test/scenarios/get-scenario-blm-calibration-results.e2e-spec.ts
  api/apps/api/test/scenarios/get-scenario-blm-calibration-results.fixtures.ts
  api/apps/api/test/scenarios/input-file.e2e-spec.ts
  api/apps/api/test/scenarios/start-scenario-calibration.e2e-spec.ts
  api/apps/api/test/scenarios/start-scenario-calibration.fixtures.ts
Labels: API, WIP

#786 ref: use of file stream in GetArchiveHandler
  api/apps/api/src/modules/clone/export/application/get-archive.handler.ts
  api/apps/api/src/modules/clone/export/application/get-archive.query.ts
  api/apps/api/src/modules/clone/export/export.module.ts
  api/apps/api/src/modules/projects/projects.controller.ts
  api/apps/api/src/modules/projects/projects.service.ts
Labels: API
