Repository Vizzuality/marxan-cloud, pull requests merged in 2022-08, with the labels that each got.

#1218 fix(front): enable save non protected areas[MARXAN-1727]
  app/hooks/map/index.ts
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/edit/planning-unit/protected-areas/categories/component.tsx
  app/layout/scenarios/edit/planning-unit/protected-areas/component.tsx
Labels: bug, Frontend, Ready to review

#1227 Preview splitted features on the map
  app/components/features/target-spf-item/types.ts
  app/hooks/features/index.ts
  app/hooks/map/constants.tsx
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/layout/scenarios/edit/features/set-up/add/list/component.tsx
  app/layout/scenarios/edit/map/component.tsx
Labels: Frontend, Ready to review, New feature

#1230 Beta: remove
  app/layout/header/component.tsx
Labels: Frontend, Ready to review, New feature

#1233 enhancement(front): add upload shapefiles extra info [MARXAN-1512]
  app/layout/scenarios/edit/features/set-up/add/add-modal/uploader/component.tsx
  app/layout/scenarios/edit/planning-unit/adjust-planning-units/buttons/uploading/component.tsx
  app/layout/scenarios/edit/planning-unit/protected-areas/categories/pa-uploader/component.tsx
Labels: enhancement, Frontend

#1234 enhancement(front): extra caution removing features [MARXAN-1751]
  app/hooks/admin/index.ts
  app/layout/scenarios/edit/features/set-up/add/list/component.tsx
Labels: enhancement, Frontend

#1235 enhancement(front): display solutions are locked on upload legacy projects [MARXAN-1754][MARXAN-1752]
  app/components/info-button/component.tsx
  app/layout/projects/all/toolbar/upload-btn/legacy-upload-modal/upload-files/component.tsx
  app/layout/projects/all/toolbar/upload-btn/legacy-upload-modal/upload-files/constants.ts
  app/layout/projects/all/toolbar/upload-btn/legacy-upload-modal/upload-files/upload-item/component.tsx
Labels: enhancement, Frontend

#1236 Map: reload map if accessToken changes
  app/layout/projects/new/map/component.tsx
  app/layout/projects/show/header/toolbar/publish-btn/publish-modal/component.tsx
  app/layout/projects/show/map/component.tsx
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/new/map/component.tsx
  app/layout/scenarios/reports/blm/map/component.tsx
  app/layout/scenarios/reports/frequency/map/component.tsx
  app/layout/scenarios/reports/solutions/selected-solution-page/map/component.tsx
  app/layout/scenarios/reports/solutions/selection-frequency-page/map/component.tsx
Labels: bug, Frontend, Ready to review

#1242 BLM: improve formatting
  app/utils/units.ts
Labels: bug, Frontend, Ready to review

#1241 Features: fix bug that when you search it removes the other features
  app/layout/scenarios/edit/features/set-up/add/add-modal/component.tsx
Labels: bug, Frontend, Ready to review

#1243 Parameters: allow 0 as default value
  app/layout/scenarios/edit/parameters/advanced-settings/component.tsx
Labels: bug, Frontend, Ready to review
