Repository Vizzuality/marxan-cloud, pull requests merged in 2023-09, with the labels that each got.

#1475 [MRXN23-416]: adds callback in header for logged users
  app/components/button/index.ts
  app/layout/header/index.tsx
  app/pages/index.tsx
  app/pages/projects/index.tsx
Labels: Frontend

#1451 FE (feat): new print layout [MRXN23-296]
  app/components/map/legend/item/component.tsx
  app/components/map/legend/types/gradient/component.tsx
  app/hooks/map/types.ts
  app/hooks/scenarios/index.ts
  app/hooks/scenarios/types.ts
  app/hooks/solutions/index.ts
  app/layout/project/sidebar/scenario/advanced-settings/blm-calibration/results/component.tsx
  app/layout/project/sidebar/scenario/solutions/overview/index.tsx
  app/layout/scenarios/reports/solutions/advanced-settings/constants.ts
  app/layout/scenarios/reports/solutions/advanced-settings/index.tsx
  app/layout/scenarios/reports/solutions/best-solution/index.tsx
  app/layout/scenarios/reports/solutions/best-solution/map/index.tsx
  app/layout/scenarios/reports/solutions/cost-surface/index.tsx
  app/layout/scenarios/reports/solutions/cost-surface/map/index.tsx
  app/layout/scenarios/reports/solutions/different-solutions/first/index.tsx
  app/layout/scenarios/reports/solutions/different-solutions/map/index.tsx
  app/layout/scenarios/reports/solutions/different-solutions/second/index.tsx
  app/layout/scenarios/reports/solutions/features/index.tsx
  app/layout/scenarios/reports/solutions/frequency/index.tsx
  app/layout/scenarios/reports/solutions/frequency/map/index.tsx
  app/layout/scenarios/reports/solutions/gap-analysis/index.tsx
  app/layout/scenarios/reports/solutions/grid/index.tsx
  app/layout/scenarios/reports/solutions/grid/map/index.tsx
  app/layout/scenarios/reports/solutions/header/component.tsx
  app/layout/scenarios/reports/solutions/header/index.ts
  app/layout/scenarios/reports/solutions/header/index.tsx
  app/layout/scenarios/reports/solutions/intro-page/component.tsx
  app/layout/scenarios/reports/solutions/intro-page/index.ts
  app/layout/scenarios/reports/solutions/pu-status/index.tsx
  app/layout/scenarios/reports/solutions/pu-status/map/index.tsx
  app/layout/scenarios/reports/solutions/resume/index.tsx
  app/layout/scenarios/reports/solutions/selected-solution-page/component.tsx
  app/layout/scenarios/reports/solutions/selected-solution-page/index.ts
  app/layout/scenarios/reports/solutions/selected-solution-page/map/index.ts
  app/layout/scenarios/reports/solutions/selected-solution-page/map/index.tsx
  app/layout/scenarios/reports/solutions/selection-frequency-page/component.tsx
  app/layout/scenarios/reports/solutions/selection-frequency-page/index.ts
  app/layout/scenarios/reports/solutions/selection-frequency-page/map/index.ts
  app/layout/scenarios/reports/solutions/settings-page/component.tsx
  app/layout/scenarios/reports/solutions/settings-page/index.ts
  app/layout/scenarios/reports/solutions/solutions-table/index.tsx
  app/layout/scenarios/reports/solutions/target-achievement/index.tsx
  app/layout/scenarios/reports/solutions/webshot-status/index.ts
  app/layout/scenarios/reports/solutions/webshot-status/index.tsx
  app/pages/api/reports/scenarios/[sid]/solutions.ts
  app/pages/reports/[pid]/[sid]/solutions.tsx
Labels: Frontend, Ready to review

#1481 [MRXN23-423]: adds feature flag for CSV feature upload
  app/components/upload-tabs/index.tsx
Labels: Frontend

#1480 [MRXN23-419]: PA selector: fixes setting default values after uploading shapefile
  app/hooks/scenarios/index.ts
  app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/index.tsx
Labels: Frontend

#1486 [MRXN23-427]: moves PU section right after PA
  app/layout/project/navigation/hooks.tsx
  app/layout/project/navigation/index.tsx
Labels: Frontend

#1487 [MRXN23-431]: renames advanced settings section
  app/layout/project/navigation/constants.ts
  app/layout/project/navigation/hooks.tsx
  app/layout/project/navigation/index.tsx
  app/layout/project/navigation/types.ts
Labels: Frontend

#1488 [MRXN23-429]: updates Gap Analysis icon
  app/layout/project/navigation/hooks.tsx
  app/svgs/navigation/gap-analysis.svg
Labels: Frontend

#1489 [MRXN23-376]: unifies upload icon
  app/components/uploader/component.stories.tsx
  app/components/uploader/component.tsx
  app/components/uploader/index.ts
  app/components/uploader/index.tsx
  app/components/uploader/types.ts
  app/layout/project/sidebar/project/inventory-panel/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/upload/index.tsx
  app/layout/projects/all/toolbar/upload-btn/component.tsx
  app/package.json
  app/svgs/ui/upload.svg
  app/yarn.lock
Labels: Frontend

#1491 dev preview of toles for feature amounts per PU [MRXN23-203]; tweak tolerance for st_repeatedpoints dynamically [MRXN23-281]
  api/apps/geoprocessing/src/modules/features/features.service.ts
  api/apps/geoprocessing/test/index.html
Labels: API, Ready to review

#1493 FE (fix): move export solutions [MRXN23-439]
  app/layout/project/sidebar/project/scenarios-list/index.tsx
  app/layout/project/sidebar/scenario/solutions/overview/index.tsx
  app/svgs/ui/table.svg
Labels: Frontend

#1495 [N/A] removes lucide-react
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/header-item/index.tsx
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
  app/package.json
  app/yarn.lock
Labels: Frontend

#1456 [FE] (feat): Inventory panel: Protected Areas [MRXN23-239]
  app/constants/file-uploader-size-limits.js
  app/hooks/map/index.ts
  app/hooks/wdpa/index.ts
  app/hooks/wdpa/types.ts
  app/layout/info/upload-wdpas.tsx
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/index.tsx
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/types.ts
  app/layout/project/sidebar/project/inventory-panel/constants.ts
  app/layout/project/sidebar/project/inventory-panel/features/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/actions-menu/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/bulk-action-menu/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/bulk-action-menu/utils.ts
  app/layout/project/sidebar/project/inventory-panel/wdpas/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/modals/delete/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/modals/edit/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/modals/upload/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/pa-uploader/index.tsx
  app/layout/projects/show/map/index.tsx
  app/services/wdpa/index.ts
  app/store/slices/projects/[id].ts
  app/types/api/wdpa.ts
Labels: Frontend

#1482 [fe](fix): scenario target achievement map [MRXN23-421]
  app/layout/project/sidebar/scenario/solutions/gap-analysis/toolbar/index.ts
  app/layout/project/sidebar/scenario/solutions/index.tsx
  app/layout/project/sidebar/scenario/solutions/target-achievement/index.tsx
  app/layout/project/sidebar/scenario/solutions/target-achievement/list/index.tsx
  app/layout/project/sidebar/scenario/solutions/target-achievement/toolbar/component.tsx
  app/layout/project/sidebar/scenario/solutions/target-achievement/toolbar/index.ts
  app/layout/project/sidebar/scenario/solutions/target-achievement/types.ts
  app/layout/scenarios/edit/map/component.tsx
  app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
Labels: Frontend

#1499 FE(fix): center map related sidebar [MRXN23-449]
  app/components/map/component.stories.tsx
  app/components/map/component.tsx
  app/components/map/controls/component.tsx
  app/layout/project/sidebar/constants.ts
  app/layout/project/sidebar/index.tsx
  app/layout/projects/new/map/component.tsx
  app/layout/projects/show/map/index.tsx
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/new/map/component.tsx
  app/package.json
  app/types/map.d.ts
  app/utils/map.ts
  app/yarn.lock
Labels: Frontend, Ready to review

#1507 [N/A]: replaces Vercel domains with production
  app/pages/_app.tsx
  app/public/robots.txt
  app/public/sitemap.xml
Labels: Frontend

#1510 [N/A]: parses WDPA endpoint
  app/hooks/wdpa/index.ts
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/types.ts
  app/layout/project/sidebar/project/inventory-panel/wdpas/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/modals/delete/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/modals/edit/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/modals/upload/index.tsx
  app/types/api/wdpa.ts
Labels: Frontend

#1514 FE (feat): Inventory Protected Areas params [MRXN23-239]
  app/hooks/wdpa/index.ts
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/modals/delete/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/modals/edit/index.tsx
  app/layout/project/sidebar/project/inventory-panel/wdpas/modals/upload/index.tsx
  app/types/api/wdpa.ts
Labels: Frontend

#1511 FE: recover run scenario goal
  app/layout/project/navigation/index.tsx
Labels: Frontend

#1515 [N/A]: removes PAs feature flag
  app/layout/project/navigation/hooks.tsx
Labels: Frontend

#1517 [MRXN23-215]: removes storybook
  app/.gitignore
  app/.storybook/.babelrc
  app/.storybook/main.js
  app/.storybook/manager.js
  app/.storybook/preview-head.html
  app/.storybook/preview.js
  app/Dockerfile
  app/components/avatar/component.stories.tsx
  app/components/breadcrumb/component.stories.tsx
  app/components/button/component.stories.tsx
  app/components/carousel/component.stories.tsx
  app/components/confirmation-prompt/component.stories.tsx
  app/components/disclaimer/component.stories.tsx
  app/components/features/intersect-item/component.stories.tsx
  app/components/features/raw-item/component.stories.tsx
  app/components/features/selected-item/component.stories.tsx
  app/components/features/target-spf-item/component.stories.tsx
  app/components/forms/checkbox/component.stories.tsx
  app/components/forms/component.stories.tsx
  app/components/forms/error/component.stories.tsx
  app/components/forms/field/component.stories.tsx
  app/components/forms/input/component.stories.tsx
  app/components/forms/label/component.stories.tsx
  app/components/forms/radio/component.stories.tsx
  app/components/forms/select/component.stories.tsx
  app/components/forms/slider/component.stories.tsx
  app/components/forms/textarea/component.stories.tsx
  app/components/gap-analysis/item/component.stories.tsx
  app/components/icon/component.stories.tsx
  app/components/info-button/component.stories.tsx
  app/components/loading/component.stories.tsx
  app/components/map/component.stories.tsx
  app/components/map/controls/component.stories.tsx
  app/components/map/controls/fit-bounds/component.stories.tsx
  app/components/map/controls/loading/component.stories.tsx
  app/components/map/controls/zoom/component.stories.tsx
  app/components/map/legend/component.stories.tsx
  app/components/modal/component.stories.tsx
  app/components/progress-bar/component.stories.tsx
  app/components/scenarios/blm-chart/component.stories.tsx
  app/components/scenarios/item/component.stories.tsx
  app/components/search/component.stories.tsx
  app/components/steps/component.stories.tsx
  app/components/table/component.stories.tsx
  app/components/tabs/component.stories.tsx
  app/components/tag/component.stories.tsx
  app/components/toast/component.stories.tsx
  app/components/tooltip/component.stories.tsx
  app/docs/authentication.stories.mdx
  app/docs/deploy.stories.mdx
  app/docs/fetching.stories.mdx
  app/docs/install.stories.mdx
  app/docs/intro.stories.mdx
  app/docs/media.stories.mdx
  app/docs/tests.stories.mdx
  app/env.default
  app/package.json
  app/public/styles/tailwind.storybook.css
  app/yarn.lock
Labels: Frontend

#1519 [N/A]: removes unused dependencies
  app/package.json
  app/yarn.lock
Labels: Frontend

#1525 [MRXN23-470]: scenario comparison legend + layer
  app/hooks/map/constants.tsx
  app/hooks/map/index.ts
  app/layout/projects/show/map/index.tsx
  app/layout/projects/show/map/legend/hooks/index.ts
  app/svgs/ui/print.svg
Labels: Frontend

#1505 [MRXN23-445/446]: Inventory / Scenario legends
  app/components/collapsible/index.tsx
  app/components/features/selected-item/component.tsx
  app/components/map/legend/component.tsx
  app/components/map/legend/group/index.tsx
  app/components/map/legend/index.ts
  app/components/map/legend/index.tsx
  app/components/map/legend/item/index.ts
  app/components/map/legend/item/index.tsx
  app/components/map/legend/types.d.ts
  app/components/map/legend/types/basic/index.ts
  app/components/map/legend/types/basic/index.tsx
  app/components/map/legend/types/choropleth/index.ts
  app/components/map/legend/types/choropleth/index.tsx
  app/components/map/legend/types/gradient/index.ts
  app/components/map/legend/types/gradient/index.tsx
  app/components/map/legend/types/matrix/index.ts
  app/components/map/legend/types/matrix/index.tsx
  app/hooks/cost-surface/index.ts
  app/hooks/features/index.ts
  app/hooks/gap-analysis/index.ts
  app/hooks/map/constants.tsx
  app/hooks/map/index.ts
  app/hooks/map/types.ts
  app/hooks/scenarios/index.ts
  app/hooks/wdpa/index.ts
  app/layout/project/reports/comparison/map/index.tsx
  app/layout/project/sidebar/project/inventory-panel/cost-surfaces/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/index.tsx
  app/layout/project/sidebar/scenario/advanced-settings/blm-calibration/component.tsx
  app/layout/project/sidebar/scenario/advanced-settings/overview/component.tsx
  app/layout/project/sidebar/scenario/grid-setup/features/add/list/component.tsx
  app/layout/project/sidebar/scenario/grid-setup/gap-analysis/list/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/protected-areas/threshold/index.tsx
  app/layout/project/sidebar/scenario/solutions/overview/index.tsx
  app/layout/project/sidebar/scenario/solutions/target-achievement/index.tsx
  app/layout/project/sidebar/scenario/solutions/target-achievement/list/index.tsx
  app/layout/projects/show/map/index.tsx
  app/layout/projects/show/map/legend/hooks/index.ts
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/edit/map/legend/hooks/index.ts
  app/layout/scenarios/new/map/component.tsx
  app/layout/scenarios/reports/solutions/best-solution/index.tsx
  app/layout/scenarios/reports/solutions/cost-surface/index.tsx
  app/layout/scenarios/reports/solutions/frequency/index.tsx
  app/layout/scenarios/reports/solutions/grid/index.tsx
  app/layout/solutions/selected/component.tsx
  app/package.json
  app/store/slices/projects/[id].ts
  app/store/slices/scenarios/edit.ts
  app/svgs/ui/print.svg
  app/types/api/feature.ts
  app/yarn.lock
Labels: Frontend

#1528 fixes sidebar blink
  app/layout/projects/show/map/index.tsx
Labels: Frontend
