Repository Vizzuality/marxan-cloud, pull requests merged in 2023-08, with the labels that each got.

#1406 [FE]: types cleanup
  app/hooks/administrative-areas/index.ts
  app/hooks/administrative-areas/types.ts
  app/hooks/countries/index.ts
  app/hooks/countries/types.ts
  app/hooks/projects/index.ts
  app/hooks/projects/types.ts
  app/hooks/scenarios/index.ts
  app/hooks/solutions/mock.ts
  app/layout/projects/all/list/item/component.tsx
  app/layout/projects/new/form/constants.ts
  app/layout/projects/new/form/country-region-selector/index.ts
  app/layout/projects/new/form/country-region-selector/index.tsx
  app/layout/projects/new/form/country-region-selector/types.ts
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/component.tsx
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/planning-unit-button/index.ts
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/planning-unit-button/index.tsx
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/planning-unit-button/types.ts
  app/layout/projects/new/form/planning-area-selector/planning-unit-grid/types.ts
  app/layout/scenarios/edit/solutions/overview/table/types.ts
  app/store/slices/scenarios/detail.ts
  app/store/slices/scenarios/edit.ts
  app/types/api-model.ts
  app/types/api/location.ts
  app/types/api/project.ts
  app/types/country-model.ts
Labels: Frontend

#1407 [MRXN23-261]: Stores sidebar visibility in redux
  app/layout/project/sidebar/index.tsx
  app/layout/projects/show/map/component.tsx
  app/package.json
  app/store/hooks.ts
  app/store/index.ts
  app/store/slices/projects/[id].ts
  app/yarn.lock
Labels: Frontend

#1408 [MRXN23-226]: new icons for navigation and amendments in user's menu
  app/layout/project/navigation/constants.ts
  app/layout/project/navigation/hooks.tsx
  app/layout/project/navigation/index.tsx
  app/layout/project/navigation/user-menu/constants.ts
  app/layout/project/navigation/user-menu/index.tsx
  app/svgs/navigation/blm-calibration.svg
  app/svgs/navigation/community.svg
  app/svgs/navigation/documentation.svg
  app/svgs/navigation/overview.svg
  app/svgs/navigation/planning-unit-status.svg
  app/svgs/navigation/planning-units.svg
  app/svgs/navigation/project-dashboard.svg
  app/svgs/navigation/protected-area.svg
  app/svgs/navigation/protected-areas.svg
  app/svgs/navigation/target.svg
  app/svgs/ui/sign-out.svg
Labels: Frontend

#1348 replaces Cypress with Playwright
  .github/workflows/cypress.yml
  .github/workflows/e2e-client.yml
  app/.eslintignore
  app/.gitignore
  app/cypress.config.ts
  app/cypress/e2e/about.cy.ts
  app/cypress/fixtures/example.json
  app/cypress/plugins/index.js
  app/cypress/support/e2e.js
  app/docs/tests.stories.mdx
  app/e2e/example.spec.ts
  app/layout/sign-in/component.tsx
  app/package.json
  app/playwright.config.ts
  app/yarn.lock
Labels: Frontend

#1427 [MRXN23-228] fix: project export loop on status actions
  app/layout/projects/show/status/actions/done.tsx
  app/layout/projects/show/status/component.tsx
Labels: Frontend

#1430 [N/A]: renames planning unit files
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions-summary/buttons/index.ts
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions-summary/buttons/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions-summary/index.ts
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions-summary/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/draw/index.ts
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/draw/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/index.ts
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/select/index.ts
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/select/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/upload/index.ts
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/upload/index.tsx
Labels: Frontend

#1441 FE (feat): upload feature by CSV [MRXN23 295]
  app/components/upload-tabs/index.tsx
  app/constants/file-uploader-size-limits.js
  app/hooks/features/index.ts
  app/hooks/projects/index.ts
  app/hooks/scenarios/index.ts
  app/layout/project/sidebar/project/inventory-panel/features/list/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/modals/upload/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/cost-surface/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/features/add/add-modal/uploader/component.tsx
Labels: Frontend, Ready to review

#1440 FE (fix): minor feedback [MRXN23 315]
  app/layout/header/index.ts
  app/layout/header/index.tsx
  app/layout/header/my-projects/component.tsx
  app/layout/header/my-projects/index.ts
  app/layout/header/user/component.tsx
  app/layout/header/user/index.ts
  app/layout/project/navigation/breadcrumbs/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/list/item/actions/index.tsx
  app/layout/projects/show/map/index.tsx
Labels: Frontend, Ready to review

#1438 FE (feat): tag uploaded feature [MRXN23 285]
  app/hooks/features/index.ts
  app/layout/project/sidebar/project/inventory-panel/features/modals/edit-bulk/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/modals/edit/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/modals/upload/index.tsx
Labels: Frontend, Ready to review

#1437 create new CostSurface and CostSurfacePuData entities in dbs [MRXN23-93]
  api/apps/api/src/app.module.ts
  api/apps/api/src/migrations/api/1691980238543-AddCostSurdaceApiDb.ts
  api/apps/api/src/modules/cost-surface/cost-surface-module-first.class.ts
  api/apps/api/src/modules/cost-surface/cost-surface.api.entity.ts
  api/apps/api/src/modules/projects/project-cost-surface.controller.ts
  api/apps/api/src/modules/projects/project.api.entity.ts
  api/apps/api/src/modules/projects/projects.controller.ts
  api/apps/api/src/modules/scenarios/scenario.api.entity.ts
  api/apps/api/test/cost-surfaces/cost-surfaces.e2e-spec.ts
  api/apps/api/test/utils/test-client/entity-seeder.ts
  api/apps/geoprocessing/src/app.module.ts
  api/apps/geoprocessing/src/migrations/geoprocessing/1692254627921-AddsCostSurfacePuDataGeoDb.ts
  api/apps/geoprocessing/src/modules/cost-surface/adapters/available-planning-units-repository.ts
  api/apps/geoprocessing/src/modules/cost-surface/adapters/pu-cost-extractor.spec.ts
  api/apps/geoprocessing/src/modules/cost-surface/adapters/pu-cost-extractor.ts
  api/apps/geoprocessing/src/modules/cost-surface/adapters/shapefile-converter.ts
  api/apps/geoprocessing/src/modules/cost-surface/adapters/typeorm-cost-surface.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/__mocks__/area.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/__mocks__/cost-surface-repo.fake.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/__mocks__/cost.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/__mocks__/geojson.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/__mocks__/get-available-puids.fake.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/__mocks__/job.data.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/__mocks__/pu-extractor.fake.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/__mocks__/shapefile-converter.fake.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/surface-cost-processor.spec.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/surface-cost-processor.ts
  api/apps/geoprocessing/src/modules/cost-surface/application/surface-cost-worker.ts
  api/apps/geoprocessing/src/modules/cost-surface/cost-surface.module.ts
  api/apps/geoprocessing/src/modules/cost-surface/ports/available-planning-units/get-available-planning-units.ts
  api/apps/geoprocessing/src/modules/cost-surface/ports/cost-surface-shapefile-record.ts
  api/apps/geoprocessing/src/modules/cost-surface/ports/persistence/cost-surface-persistence.port.ts
  api/apps/geoprocessing/src/modules/cost-surface/ports/planning-unit-cost.ts
  api/apps/geoprocessing/src/modules/cost-surface/ports/pu-extractor/pu-extractor.port.ts
  api/apps/geoprocessing/src/modules/cost-surface/ports/shapefile-converter/shapefile-converter.port.ts
  api/apps/geoprocessing/test/integration/cost-surface/cost-surface-job/process-shapefile-with-cost-surface.e2e-spec.ts
  api/apps/geoprocessing/test/integration/cost-surface/cost-surface-job/steps/world.ts
  api/apps/geoprocessing/test/integration/cost-surface/cost-surface-repo/cost-surface-update.e2e-spec.ts
  api/apps/geoprocessing/test/jest-e2e.json
  api/libs/artifact-cache/src/surface-cost-queue-name.ts
  api/libs/cost-surfaces/src/cost-surface-pu-data.geo.entity.ts
  api/libs/cost-surfaces/src/index.ts
  api/libs/cost-surfaces/tsconfig.lib.json
  api/libs/planning-unit-geometry/src/projects-pu.geo.entity.ts
  api/package.json
  api/tsconfig.json
Labels: API, WIP

#1450 [MRXN23-287]: adds Gap Analysis icon to navigation
  app/layout/project/navigation/hooks.tsx
  app/layout/project/sidebar/scenario/grid-setup/gap-analysis/index.tsx
  app/layout/project/sidebar/scenario/solutions/gap-analysis/index.tsx
  app/svgs/navigation/gap-analysis.svg
Labels: Frontend

#1444 [fe]: Disable solutions when scenario have not ran an scenario [MRXN23-321]
  app/hoc/scenarios.ts
  app/hooks/scenarios/index.ts
  app/hooks/scenarios/types.ts
  app/layout/header/title/component.tsx
  app/layout/project/navigation/constants.ts
  app/layout/project/navigation/index.tsx
  app/layout/project/navigation/submenu/index.tsx
  app/layout/project/sidebar/project/scenarios-list/index.tsx
  app/layout/project/sidebar/scenario/advanced-settings/blm-calibration/results/component.tsx
  app/layout/projects/show/scenarios/component.tsx
  app/layout/scenarios/new/name/index.tsx
  app/layout/sidebar/submenu/index.tsx
Labels: Frontend, Ready to review

#1447 [MRXN23-284]: Unify lists for features / protected areas / cost surface
  app/layout/project/navigation/types.ts
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/header-item/index.tsx
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/header-item/types.ts
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/index.tsx
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/types.ts
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/types.ts
  app/layout/project/sidebar/project/inventory-panel/constants.ts
  app/layout/project/sidebar/project/inventory-panel/cost-surface/index.tsx
  app/layout/project/sidebar/project/inventory-panel/cost-surface/info/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/actions-menu/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/bulk-action-menu/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/info/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/list/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/list/item/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/modals/edit-bulk/index.tsx
  app/layout/project/sidebar/project/inventory-panel/index.tsx
  app/layout/project/sidebar/project/inventory-panel/protected-areas/footer/index.tsx
  app/layout/project/sidebar/project/inventory-panel/protected-areas/index.tsx
  app/layout/project/sidebar/project/inventory-panel/types.ts
  app/layout/sidebar/constants.ts
  app/layout/sidebar/hooks.tsx
  app/layout/sidebar/index.tsx
  app/layout/sidebar/submenu/index.tsx
  app/layout/sidebar/types.ts
  app/layout/sidebar/user-menu/constants.ts
  app/layout/sidebar/user-menu/index.tsx
  app/pages/projects/[pid]/index.tsx
  app/svgs/ui/edit.svg
  app/svgs/ui/tag.svg
Labels: Frontend

#1462 [MRXN23-397]: fixes PU map
  app/hooks/scenarios/index.ts
  app/layout/scenarios/edit/map/component.tsx
Labels: Frontend

#1466 [MRXN23-409]: updates list of features correctly after uploading shapefile
  app/layout/project/sidebar/scenario/grid-setup/features/add/add-modal/uploader/component.tsx
Labels: Frontend

#1465 [MRXN23-410]: updates planning unit status tab order
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions-summary/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/tabs/index.tsx
  app/layout/scenarios/edit/map/component.tsx
Labels: Frontend

#1467 [MRXN23-395]: updates protected area step improve
  app/hooks/map/constants.tsx
  app/hooks/map/index.ts
Labels: Frontend

#1471 [MRXN23-399]: improves layout and responsiveness of lists
  app/layout/project/sidebar/index.tsx
  app/layout/project/sidebar/project/inventory-panel/components/inventory-table/index.tsx
  app/layout/project/sidebar/project/inventory-panel/features/index.tsx
  app/layout/project/sidebar/project/inventory-panel/index.tsx
  app/layout/project/sidebar/project/scenarios-list/index.tsx
  app/layout/project/sidebar/scenario/advanced-settings/blm-calibration/component.tsx
  app/layout/project/sidebar/scenario/advanced-settings/overview/component.tsx
  app/layout/project/sidebar/scenario/grid-setup/features/add/component.tsx
  app/layout/project/sidebar/scenario/grid-setup/features/add/list/component.tsx
  app/layout/project/sidebar/scenario/grid-setup/gap-analysis/index.tsx
  app/layout/project/sidebar/scenario/solutions/gap-analysis/index.tsx
  app/layout/scenarios/sidebar/component.tsx
Labels: Frontend

#1472 [FE]: adjusts bbox padding for some maps
  app/layout/projects/show/map/index.tsx
  app/layout/scenarios/new/map/component.tsx
Labels: Frontend

#1468 [MRXN23-408]: ensures PA list in scenarios keeps up to date after uploading a protected area
  app/hooks/wdpa/index.ts
  app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/index.tsx
  app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/pa-uploader/index.tsx
Labels: Frontend

#1473 [FE]: removes job done status as condition to display status progress
  app/hooks/projects/index.ts
  app/layout/projects/show/map/index.tsx
  app/layout/projects/show/status/component.tsx
  app/layout/projects/show/status/utils.tsx
  app/layout/scenarios/edit/map/component.tsx
  app/layout/scenarios/reports/blm/map/component.tsx
  app/layout/scenarios/reports/frequency/map/component.tsx
  app/layout/scenarios/reports/solutions/selected-solution-page/map/component.tsx
  app/layout/scenarios/reports/solutions/selection-frequency-page/map/component.tsx
Labels: Frontend

#1470 [MRXN23-407]: fixes project creation through shapefile with grid
  app/layout/projects/new/form/component.tsx
Labels: Frontend

#1476 [MRXN23-402]: adds query invalidation for target-spf data
  app/hooks/features/index.ts
  app/layout/project/sidebar/scenario/grid-setup/features/targets/list/component.tsx
Labels: Frontend
